NGInlineItem: Rename FontFallbackPriority() to GetFontFallbackPriority()
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    In file included from ../../third_party/blink/renderer/core/layout/ng/inline/ng_inline_node_data.h:9:0,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_inline_node.h:10,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_line_breaker.h:11,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_line_breaker.cc:5:
    ../../third_party/blink/renderer/core/layout/ng/inline/ng_inline_item.h:135:47: error: declaration of ‘blink::FontFallbackPriority blink::NGInlineItem::FontFallbackPriority() const’ [-fpermissive]
       FontFallbackPriority FontFallbackPriority() const;
                                                   ^~~~~
    In file included from ../../third_party/blink/renderer/platform/fonts/font_cache.h:44:0,
                     from ../../third_party/blink/renderer/platform/fonts/font_fallback_list.h:26,
                     from ../../third_party/blink/renderer/platform/fonts/font.h:29,
                     from gen/third_party/blink/renderer/core/style/computed_style_initial_values.h:31,
                     from gen/third_party/blink/renderer/core/computed_style_base.h:25,
                     from ../../third_party/blink/renderer/core/style/computed_style.h:30,
                     from ../../third_party/blink/renderer/core/layout/layout_object.h:48,
                     from ../../third_party/blink/renderer/core/layout/api/line_layout_item.h:9,
                     from ../../third_party/blink/renderer/core/layout/layout_block_flow.h:42,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_inline_node.h:9,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_line_breaker.h:11,
                     from ../../third_party/blink/renderer/core/layout/ng/inline/ng_line_breaker.cc:5:
    ../../third_party/blink/renderer/platform/fonts/font_fallback_priority.h:14:12: error: changes meaning of ‘FontFallbackPriority’ from ‘enum class blink::FontFallbackPriority’ [-fpermissive]
     enum class FontFallbackPriority {
                ^~~~~~~~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |FontFallbackPriority()| method can
change the meaning of references to the |FontFallbackPriority| enum in the
code depending on where it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetFontFallbackPriority()| after commit
06e705c9 ("[LayoutNG] Segment NGInlineItem by RunSegmenter").

Bug: 819294
Cq-Include-Trybots: master.tryserver.chromium.linux:linux_layout_tests_layout_ng
Change-Id: If50741d932c9068ec024cc79c01b444dc40b39a5
Reviewed-on: https://chromium-review.googlesource.com/1086934
Commit-Queue: Koji Ishii <kojii@chromium.org>
Reviewed-by: Koji Ishii <kojii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#564536}