Revert of Make VR screen tap tests more stable (patchset #6 id:100001 of https://codereview.chromium.org/2768583002/ )
Reason for revert:
Breaking compile on several bots including Android x64 builder:
  symbol:   class OnDispatchTouchEventCallback
  location: class WebVrTest
../../chrome/android/javatests/src/org/chromium/chrome/browser/vr_shell/WebVrTest.java:269: error: cannot find symbol
        ((VrShellImpl) VrShellDelegate.getVrShellForTesting()

Original issue's description:
> Make VR screen tap tests more stable
>
> The single tap sent during the VR screen tap tests wasn't always
> getting registered since device response can be a bit slow during
> the VR transition. For the Cardboard case, wait on Javascript to say
> it received another click event. For the Daydream case, wait on VrShell
> saying its parent has consumed the event before checking.
> BUG=
>
> Review-Url: https://codereview.chromium.org/2768583002
> Cr-Commit-Position: refs/heads/master@{#460452}
> Committed: https://chromium.googlesource.com/chromium/src/+/3e2ce51e88f19f0cc5196284f580583ddd4dbd9a

TBR=dtrainor@chromium.org,tedchoc@chromium.org,mthiesse@chromium.org,bsheedy@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2782963002
Cr-Commit-Position: refs/heads/master@{#460490}