Revert "[Android] Replace TintedImageView and TintedImageButton"
This reverts commit af3f31af03ff6f9ab5d71c3c73a294094f1b5538.

Reason for revert: Breaks Android buildbot runs with errors like:
  ```../../chrome/android/java/src/org/chromium/chrome/browser/toolbar/IncognitoToggleTabLayout.java:18: error: cannot find symbol
  import org.chromium.chrome.browser.widget.TintedImageView;```
 
Full run here: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8933828868736954944/+/steps/compile__with_patch_/0/stdout


Original change's description:
> [Android] Replace TintedImageView and TintedImageButton
> 
> This CL replaces Chrome-specific tinting view classes with their
> AppCompat equivalents: TintedImageView -> AppCompatImageView and
> TintedImageButton -> AppCompatImageButton.
> 1. Entries in XML layouts have fully qualified names because some
>    layouts are inflated outside AppCompatActivity, so AppCompat magic
>    doesn't work for them.
> 2. AppCompatImageView doesn't have setTint, so
>    ImageViewCompat.setImageTintList is used instead.
> 3. AppCompatImageView uses 'tint' XML attribute instead of 'chrometint',
>    so these are replaced, too.
> 
> Bug: 727723
> Change-Id: Id1614af64fa6ddd7cfdc6e12ad565ed32628d3c1
> Reviewed-on: https://chromium-review.googlesource.com/1245786
> Commit-Queue: Boris Sazonov <bsazonov@chromium.org>
> Reviewed-by: Ted Choc <tedchoc@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#595500}

TBR=tedchoc@chromium.org,twellington@chromium.org,bsazonov@chromium.org,huayinz@chromium.org

Change-Id: I83efa81fce074f24f330281460b2685f1765f0e3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 727723
Reviewed-on: https://chromium-review.googlesource.com/1255456
Reviewed-by: Kevin Marshall <kmarshall@chromium.org>
Commit-Queue: Kevin Marshall <kmarshall@chromium.org>
Cr-Commit-Position: refs/heads/master@{#595625}