Revert of Fix double ripple on activated flood fill ripple (patchset #1 id:1 of https://codereview.chromium.org/2640383002/ )
Reason for revert:
Causes compile-time failure:

../../ui/views/animation/flood_fill_ink_drop_ripple.cc:335:46: error: no viable conversion from 'ui::LayerAnimationElement *' to 'std::unique_ptr<ui::LayerAnimationElement>'
 std::unique_ptr<ui::LayerAnimationElement> element =

Original issue's description:
> Fix double ripple on activated flood fill ripple
>
> When switching from pending to activated state, there is no need to do
> more animations as the final state of animations for these states are
> the same. Otherwise, janks on slow devices might create some unwanted
> effects like double ripples.
>
> BUG=670831
> TEST=manual
>
> Review-Url: https://codereview.chromium.org/2615613003
> Cr-Commit-Position: refs/heads/master@{#443366}
> (cherry picked from commit 30c4e21c362f23e2a40c5bba0483e59c3fc672ff)
>
> Review-Url: https://codereview.chromium.org/2640383002 .
> Cr-Commit-Position: refs/branch-heads/2924@{#801}
> Cr-Branched-From: 3a87aecc31cd1ffe751dd72c04e5a96a1fc8108a-refs/heads/master@{#433059}
> Committed: https://chromium.googlesource.com/chromium/src/+/fce107cf1b0ff1ed005d256e72feb2737232c9d3

TBR=
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=670831

Review-Url: https://codereview.chromium.org/2644943002
Cr-Commit-Position: refs/branch-heads/2924@{#802}
Cr-Branched-From: 3a87aecc31cd1ffe751dd72c04e5a96a1fc8108a-refs/heads/master@{#433059}