Revert "[base] Implement std::size(), std::empty() and std::data()"
This reverts commit f6c12979e9fd4b9a65b6a88da966ead7014cd227.

Reason for revert: <INSERT REASONING HERE>
Breaks ios-device-xcode-clang and ios-simulator-xcode-clang
../../base/stl_util_unittest.cc:120:33: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    std::array<int, 4> array = {1, 2, 3, 4};
                                ^~~~~~~~~~
                                {         }
https://ci.chromium.org/buildbot/chromium.mac/ios-device-xcode-clang/57071

Original change's description:
> [base] Implement std::size(), std::empty() and std::data()
> 
> This change provides C++14 implementations of C++17's std::size(),
> std::empty() and std::data().
> 
> Bug: 828324
> Change-Id: If1b83826a23b26fd557f7854962bcbc771a7ffe0
> Reviewed-on: https://chromium-review.googlesource.com/992236
> Commit-Queue: Jan Wilken Dörrie <jdoerrie@chromium.org>
> Reviewed-by: kylechar <kylechar@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#550137}

TBR=dcheng@chromium.org,kylechar@chromium.org,jdoerrie@chromium.org

Change-Id: I0335a72133de226a435c1f215f886850a108ef01
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 828324
Reviewed-on: https://chromium-review.googlesource.com/1011565
Reviewed-by: Menglu Huang <huangml@chromium.org>
Commit-Queue: Menglu Huang <huangml@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#550430}(cherry picked from commit fc3f3d7a722fe71c9f6d9c63b97a5b0b1c57c6e9)
Reviewed-on: https://chromium-review.googlesource.com/1019616
Reviewed-by: Mike Dougherty <michaeldo@chromium.org>
Cr-Commit-Position: refs/branch-heads/3396@{#137}
Cr-Branched-From: 9ef2aa869bc7bc0c089e255d698cca6e47d6b038-refs/heads/master@{#550428}