CacheStorageRef: Drop noexcept from the default constructor
This fixes the GCC build after fdf95b6 ("CacheStorage: Refactor handle
ref-counting"):

    ../../content/browser/background_fetch/storage/match_requests_task.cc: In constructor ‘content::background_fetch::MatchRequestsTask::MatchRequestsTask(content::background_fetch::DatabaseTaskHost*, content::BackgroundFetchRegistrationId, std::unique_ptr<content::BackgroundFetchRequestMatchParams>, content::background_fetch::MatchRequestsTask::SettledFetchesCallback)’:
    ../../content/browser/background_fetch/storage/match_requests_task.cc:29:25: error: use of deleted function ‘content::CacheStorageRef<TargetType>::CacheStorageRef() [with TargetType = content::CacheStorageCache]’
           weak_factory_(this) {}
                             ^

With GCC, having that noexcept marker would require all members to be
marked with noexcept themselves (in this case, base::WeakPtr and its
hierarchy). While that could also be possible, the style guide only
explicitly mentions move constructors/assignment operators, and it is not
clear if having a noexcept default constructor brings any benefits.

clang is fine because we pass -fno-exceptions and it disables the same error
there, while GCC continues to raise it (bug 843143 and its corresponding CL
have a longer discussion on this issue).

Bug: 819294
Change-Id: I726cbc8d9e0d624c530a835373c0dbad32279b78
Reviewed-on: https://chromium-review.googlesource.com/c/1350954
Reviewed-by: Hiroki Nakagawa <nhiroki@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#611035}