[Android] Fix x86 build after 1f6acfe7dd08.
../../content/common/sandbox_linux/android/sandbox_bpf_base_policy_android.cc:45:10:
  error: 'sandbox::bpf_dsl::BoolExpr content::{anonymous}::RestrictSocketArguments()'
  defined but not used [-Werror=unused-function]

BUG=663249,655300
TBR=rickyz@chromium.org

Review-Url: https://codereview.chromium.org/2483253002
Cr-Commit-Position: refs/heads/master@{#430621}