Revert of base: Remove using:: declaration from version.h header. (patchset #24 id:450001 of https://codereview.chromium.org/1281313003/ )
Reason for revert:

Blocks today's Canary

Broke all official bots, e.g. http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/1926/steps/compile/logs/stdio

c:\b\build\slave\google-chrome-rel-win\build\src\chrome\browser\component_updater\pepper_flash_component_installer.cc(326) :error C3861: 'Version': identifier not found

Original issue's description:
> base: Remove using:: declaration from version.h header.
>
> BUG=None
> R=brettw@chromium.org
>
> Committed: https://crrev.com/9c2f5dc9c732beb936b41d073bf5ec7adefb0872
> Cr-Commit-Position: refs/heads/master@{#344088}

R=brettw@chromium.org,tfarina@chromium.org,thakis@chromium.org,ricea@chromium.org,nyerramilli@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=522329

Review URL: https://codereview.chromium.org/1301883002

Cr-Commit-Position: refs/heads/master@{#344138}
(cherry picked from commit 37be69cfdb84f4fdabcb779f443d18bbc04f1ffb)

Review URL: https://codereview.chromium.org/1284173005

Cr-Commit-Position: refs/branch-heads/2487@{#3}
Cr-Branched-From: cdef62cbf79acd343ff2b649efb089c39a6af076-refs/heads/master@{#344105}