Add missing algorithm header to webcursor_ozone
This fixes the following error:

../../content/common/cursors/webcursor_ozone.cc:59:77: error: no matching function for call to 'min(<brace-enclosed initializer list>)'
        static_cast<float>(maximum_cursor_size_.height()) / bitmap->height()});
                                                                             ^
Bug: 819294

Change-Id: I248e8b0199d150bb22cf0609c3588048e6405bfe
Reviewed-on: https://chromium-review.googlesource.com/c/1454356
Reviewed-by: Bret Sepulveda <bsep@chromium.org>
Commit-Queue: Maksim Sisov <msisov@igalia.com>
Cr-Commit-Position: refs/heads/master@{#629520}