Revert "Move components/safe_browsing_db to components/safe_browsing/db"
This reverts commit 155fea2f909d0b42cb32817d473e2a2673e22e5a.

Reason for revert: does not compile

https://build.chromium.org/p/chromium/builders/Linux%20x64/builds/49275

../../chrome/browser/safe_browsing/protocol_parser.cc:23:10: fatal error: 'components/safe_browsing_db/metadata.pb.h' file not found
#include "components/safe_browsing_db/metadata.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> Move components/safe_browsing_db to components/safe_browsing/db
> 
> Move the remaining contents of compontents/safe_browsing_db into
> the safe_browsing component and delete the safe_browsing_db
> component completely.
> 
> Update DEPS, build files, and all relevant includes.
> 
> BUG=668515
> TBR=thestig@chromium.org,sgurun@chromium.org,battre@chromium.org,blundell@chromium.org
> 
> Change-Id: Ifb3ee4448ce4b9890e0546e6526563e3a4e40a09
> Reviewed-on: https://chromium-review.googlesource.com/660740
> Commit-Queue: Tim Volodine <timvolodine@chromium.org>
> Reviewed-by: Selim Gurun <sgurun@chromium.org>
> Reviewed-by: Dominic Battré <battre@chromium.org>
> Reviewed-by: Tim Volodine <timvolodine@chromium.org>
> Reviewed-by: Lei Zhang <thestig@chromium.org>
> Reviewed-by: Colin Blundell (slow until Sept 25) <blundell@chromium.org>
> Reviewed-by: Varun Khaneja <vakh@chromium.org>
> Reviewed-by: Jialiu Lin <jialiul@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#503083}

TBR=thestig@chromium.org,jam@chromium.org,battre@chromium.org,blundell@chromium.org,sgurun@chromium.org,timvolodine@chromium.org,vakh@chromium.org,jialiul@chromium.org

Change-Id: I60f196fb7abf838f69f568818da232e8844dde15
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 668515
Reviewed-on: https://chromium-review.googlesource.com/674963
Reviewed-by: vitaliii <vitaliii@chromium.org>
Commit-Queue: vitaliii <vitaliii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#503086}