Move highest policy id into constant and ensure its correctness in PRESUBMIT
Example error message:
Error: 'highest_id_currently_used' must be set to the highest policy id
in use, which is currently 451 (vs 450).

Bug: 844412
Test: ran git cl presubmit
Change-Id: I75dfb8bbbec8d0a39ed579760e3f3a5390ed88e9
Reviewed-on: https://chromium-review.googlesource.com/1078311
Commit-Queue: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Lutz Justen <ljusten@chromium.org>
Reviewed-by: Julian Pastarmov <pastarmovj@chromium.org>
Cr-Commit-Position: refs/heads/master@{#564006}