openvr: Fix license path in README.chromium.
Use Unix-style path separators instead of Windows ones; the latter cause
tools/licenses.py to fail to recognize the file:

    licenses.LicenseError: License file not found. Either add a file named
    LICENSE, import upstream's COPYING if available, or add a 'License
    File:' line to README.chromium with the appropriate path.

Change-Id: I40e86c5f62e7a8fe8d133474dfaa212d67944416
Reviewed-on: https://chromium-review.googlesource.com/651422
Reviewed-by: Brandon Jones <bajones@chromium.org>
Commit-Queue: Raphael Kubo da Costa (rakuco) <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#499971}