Revert of Fix VS 2015 Update 2 specific bug (patchset #3 id:40001 of https://codereview.chromium.org/1806743002/ )
Reason for revert:
This was a compiler bug workaround and the bug was fixed long ago. Note that
the #include "gpu/gpu_export.h" line that was added for the workaround is
being left in because it is now needed.

Original issue's description:
> Fix VS 2015 Update 2 specific bug
>
> When building Chrome with VS 2015 Update 2 RC there is a compiler error:
>
> 1>  texture_definition.cc
> 1>base/memory/ref_counted.h(414): error C2027: use of undefined type 'gpu::gles2::GLStreamTextureImage'
> 1>  gpu/command_buffer/service/texture_manager.h(31): note: see declaration of 'gpu::gles2::GLStreamTextureImage'
> 1>  base/memory/ref_counted.h(413): note: while compiling class template member function 'void scoped_refptr<gpu::gles2::GLStreamTextureImage>::AddRef(T *)'
>
> This is caused by a compiler bug, together with a type trait used in
> std::vector:
> https://twitter.com/StephanTLavavej/status/710191543840219136
>
> A VS bug has been filed at:
> https://connect.microsoft.com/VisualStudio/feedback/details/2475971
>
> Bug 595189 has a more minimal repro.
>
> BUG=440500,595189
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.win:win_optional_gpu_tests_rel;tryserver.chromium.mac:mac_optional_gpu_tests_rel
>
> Committed: https://crrev.com/4d9ecc15b1ca04d30113408a4d2c428456176ce0
> Cr-Commit-Position: refs/heads/master@{#381640}

# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=440500,595189
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel

Review-Url: https://codereview.chromium.org/2710683014
Cr-Commit-Position: refs/heads/master@{#453704}