Fix missing build dependency in //extensions/utility
Tree is closed because of this.

http://build.chromium.org/p/chromium/builders/Win/builds/32969/

In file included from ../../extensions/utility/unpacker.cc:20:
In file included from ../../content/public/common/common_param_traits.h:21:
In file included from ../../content/public/common/common_param_traits_macros.h:25:
../../ui/accessibility/ax_node_data.h:14:10: fatal error: 'ui/accessibility/ax_enums.h' file not found

content_common.gypi has export_dependent_settings for ax_gen, but
extensions/utility's dependency on content_common was missing.

NOTRY=true
NOTREECHECKS=true

Review URL: https://codereview.chromium.org/1192783002

(cherry picked from commit eeda21f259f16daefc9a23ba947e92910a9014eb)

Cr-Original-Commit-Position: refs/heads/master@{#335222}
Cr-Commit-Position: refs/branch-heads/2436@{#9}
Cr-Branched-From: e8ebe017f7a9f039749b395bcbefe8f699263528-refs/heads/master@{#335190}