Revert of Port Chromium OS touch noise filtering to Chromium (patchset #8 id:410001 of https://codereview.chromium.org/991533002/)
Reason for revert:
This patch breaks the PFQ for 32/64 bit due to some string conversion problems:

0.2346.0_rc-r1: ../../../../../../../home/chrome-bot/chrome_root/src/ui/events/ozone/evdev/touch_noise/single_position_touch_noise_filter.cc:100:63: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'int64 {aka long long int}' [-Werror=format=] chromeos-chrome-43.0.2346.0_rc-r1: touch.tracking_id, max_duration.InMilliseconds());
should I revert this - or do you want to land a patch for it?
Oh - there is also another one:
0.2346.0_rc-r1: ../../../../../../../home/chrome-bot/chrome_root/src/ui/events/ozone/evdev/touch_noise/horizontally_aligned_touch_noise_filter.cc: In member function 'virtual void ui::HorizontallyAlignedTouchNoiseFilter::Filter(const std::vector<ui::InProgressTouchEvdev>&, base::TimeDelta, std::bitset<20u>*)': chromeos-chrome-43.0.2346.0_rc-r1: ../../../../../../../home/chrome-bot/chrome_root/src/ui/events/ozone/evdev/touch_noise/horizontally_aligned_touch_noise_filter.cc:39:66: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'int64 {aka long long int}' [-Werror=format=] chromeos-chrome-43.0.2346.0_rc-r1: other_touch.tracking_id, other_touch.x, other_touch.y);

Original issue's description:
> Port Chromium OS touch noise filtering to Chromium. The Chromium OS
> touch noise filtering is at
> https://chromium.googlesource.com/chromiumos/platform/touch_noise_filter/+/master
>
> When a touch is detected as touch noise, an ET_TOUCH_CANCELLED event is sent and
> all of the subsequent events for that touch are dropped. A "touch press"
> initiates a new touch.
>
> BUG=407840
> TEST=TouchNoiseFinderTest.*, TouchEventConverterEvdevTouchNoiseTest.*
>
> Committed: https://crrev.com/1df4aa125090c601b1a18c4354b8ca9323cb4c79
> Cr-Commit-Position: refs/heads/master@{#322293}

TBR=flackr@chromium.org,spang@chromium.org,pkotwicz@google.com,sadrul@chromium.org,pkotwicz@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=407840

Review URL: https://codereview.chromium.org/1033933004

Cr-Commit-Position: refs/heads/master@{#322415}
(cherry picked from commit de2de99a0e380623ea8d2796578848fdcdc3f1ad)

Review URL: https://codereview.chromium.org/1002383003

Cr-Commit-Position: refs/branch-heads/2346@{#6}
Cr-Branched-From: bb148160238aa54b21001d354556701ea778d96a-refs/heads/master@{#322348}