webkitpy: Merge script fix windows directory removing.
Attempt to remove a directory tree multiple times as on Windows a
process which is currently closing could still have a file open in the
directory.

Also continue going even if we fail to remove the directory.

The merge script currently sometimes fails on Windows with the following
error;
-------------------------
Traceback (most recent call last):
  File "E:\b\c\b\WebKit_Win___RandomOrder\src\third_party\WebKit\Tools\Scripts\merge-layout-test-results", line 185, in <module>
    main(sys.argv[1:])
  File "E:\b\c\b\WebKit_Win___RandomOrder\src\third_party\WebKit\Tools\Scripts\merge-layout-test-results", line 161, in main
    shutil.rmtree(args.output_directory)
  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "E:\b\depot_tools\python276_bin\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'E:\\b\\rr\\tmpxu2pfv\\w'
WARNING:root:merge_cmd had non-zero return code: 1
-------------------------

BUG=717347,524758

Review-Url: https://codereview.chromium.org/2862173002
Cr-Commit-Position: refs/heads/master@{#469588}