Revert of [Android] Mark infobars as gone when they are off the screen (patchset #3 id:40001 of https://codereview.chromium.org/2662613003/ )
Reason for revert:
Suspected for causing failures on testers:

org.chromium.chrome.browser.infobar.InfoBarContainerTest#testAddAndDismissSurfaceFlingerOverlays (run #2):
java.util.concurrent.TimeoutException: InfoBar not added.
	at org.chromium.base.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:183)
	at org.chromium.base.test.util.CallbackHelper.waitForCallback(CallbackHelper.java:211)
	at org.chromium.chrome.test.util.InfoBarTestAnimationListener.addInfoBarAnimationFinished(InfoBarTestAnimationListener.java:50)

BUG=686734

Original issue's description:
> [Android] Mark infobars as gone when they are off the screen
>
> Infobars are translated off the screen when users scroll up. Yet they
> still are thought as non-transparent regions on top of surface view.
> This CL optimizes this case by setting the visibility to gone when
> infobars are not visible.
>
> BUG=661560
>
> Review-Url: https://codereview.chromium.org/2662613003
> Cr-Commit-Position: refs/heads/master@{#446869}
> Committed: https://chromium.googlesource.com/chromium/src/+/45d5cd05e3c01ddbaef79b0d469f34d1c50215f9

TBR=tedchoc@chromium.org,ianwen@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=661560

Review-Url: https://codereview.chromium.org/2665663003
Cr-Commit-Position: refs/heads/master@{#446984}