Revert of Use TaskScheduler instead of blocking pool in wizard_controller.cc. (patchset #3 id:40001 of https://codereview.chromium.org/2671263002/ )
Reason for revert:
Compile failure on official builds.

Link: https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/29028/

error like wizard_controller.cc:727:7:error: invalid argument type 'void' to unary expression

Original issue's description:
> Use TaskScheduler instead of blocking pool in wizard_controller.cc.
>
> The blocking pool is being deprecated in favor of TaskScheduler.
>
> BUG=667892
> R=alemate@chromium.org
>
> Review-Url: https://codereview.chromium.org/2671263002
> Cr-Commit-Position: refs/heads/master@{#448504}
> Committed: https://chromium.googlesource.com/chromium/src/+/51464e865861790a1c332b8fc0d7ad7824dd3170

TBR=alemate@chromium.org,fdoray@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=667892

Review-Url: https://codereview.chromium.org/2678243002
Cr-Commit-Position: refs/heads/master@{#448516}