Add public_deps for //components/toolbar:test_support and //components/search_engines
//components/toolbar details:
test_toolbar_model.h includes toolbar_model.h, therefore :toolbar is part of :test_support public interface.

Example error:
In file included from ../../ios/chrome/browser/ui/toolbar/toolbar_model_impl_ios_unittest.mm:14:
In file included from ../../components/toolbar/test_toolbar_model.h:13:
In file included from ../../components/toolbar/toolbar_model.h:14:
In file included from ../../components/security_state/core/security_state.h:16:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~

//components/search_engines details:
template_url_service.h includes files from these targets (thus they are part of its public interface), but they weren't in public_deps.

Example error:
In file included from ../../ios/chrome/browser/physical_web/start_physical_web_discovery.mm:11:
In file included from ../../components/search_engines/template_url_service.h:23:
In file included from ../../components/google/core/browser/google_url_tracker.h:17:
In file included from ../../net/url_request/url_fetcher.h:19:
In file included from ../../net/url_request/url_request.h:26:
In file included from ../../net/base/net_error_details.h:9:
In file included from ../../net/http/http_response_info.h:14:
In file included from ../../net/ssl/ssl_info.h:20:
In file included from ../../net/ssl/ssl_config.h:12:
In file included from ../../net/cert/x509_certificate.h:25:
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~

BUG=none

Review-Url: https://codereview.chromium.org/2872153002
Cr-Commit-Position: refs/heads/master@{#470692}