Minimal thread-safety annotations for base::AutoLock.
This CL adds minimal thread-safety annotations for base::AutoLock.
Note that direct usage of base::Lock is not covered by this CL
(i.e. it won't be automatically analysed after this CL).


Thanks to the added base::AutoLock annotations, an example
GUARDED_BY annotation could be added to ChildProcessSecurityPolicyImpl:

  base::flat_set<url::Origin> isolated_origins_ GUARDED_BY(lock_);

Because of the new GUARDED_BY annotation forgetting to take a lock:

  // ad-hoc test of lock annotations // base::AutoLock lock(lock_);
  isolated_origins_.insert(origins_to_add.begin(), origins_to_add.end());

would result in the following compile error:

    ../../content/browser/child_process_security_policy_impl.cc:1236:3:
    error: reading variable 'isolated_origins_' requires holding mutex 'lock_'
    [-Werror,-Wthread-safety-analysis]
      isolated_origins_.insert(origins_to_add.begin(), origins_to_add.end());
      ^


This CL requires a few workarounds to deal with known issues:

- Thread annotation macros have to become no-ops on Mac to deal
  with https://bugs.llvm.org/show_bug.cgi?id=38896

- base::OptionalBase::FreeIfNeeded has to be annotated with
  NO_THREAD_SAFETY_ANALYSIS because of https://crbug.com/881875#c1

- Uses of base::AutoLock::AlreadyAcquired have to be annotated with
  NO_THREAD_SAFETY_ANALYSIS until we can add more annotations
  to base::Lock (see https://crbug.com/881903).

- Reversal of the order of QUIC_EXPORT_PRIVATE and LOCKABLE
  in net/third_party/quic/platform/api/quic_mutex.h to ensure
  that the build will succeed on Windows.  LOCKABLE expands
  to __attribute__((lockable)) and QUIC_EXPORT_PRIVATE expands to
  __declspec(dllexport) (or dllimport) and in a class declaration the
  former must come before the latter.


Bug: 881875
Cq-Include-Trybots: luci.chromium.try:ios-simulator-cronet;master.tryserver.chromium.android:android_cronet_tester
Change-Id: Id94e42fd730b7ba69e34651e6cf616420683a20c
Reviewed-on: https://chromium-review.googlesource.com/1213272
Reviewed-by: Paul Jensen <pauljensen@chromium.org>
Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
Reviewed-by: Charlie Reis <creis@chromium.org>
Reviewed-by: Zhongyi Shi <zhongyi@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/master@{#591776}