Revert "Abandon user sign in when policy is retrieved before session started."
This reverts commit 1de6fb83edb4dccdfd53ee5db5ae8b6b59fb24dc.

Reverting due to the broken compilation of Chrome:
  src/chromeos/dbus/session_manager_client.cc:118:36:
  error: no member named 'dbus_error' in namespace 'login_manager'

This error is due to the DEPS roll of third_party/cros_system_api
not being performed correctly.

BUG=689206,722558

https: //chromium.googlesource.com/chromium/src/+/1de6fb83edb4dccdfd53ee5db5ae8b6b59fb24dc
Review-Url: https://codereview.chromium.org/2890433002 .
Cr-Commit-Position: refs/branch-heads/3071@{#579}
Cr-Branched-From: a106f0abbf69dad349d4aaf4bcc4f5d376dd2377-refs/heads/master@{#464641}