Revert 290360 "Docserver: Introduce GitilesFileSystem"
This fails webview_licenses.py:

http://build.chromium.org/p/chromium.linux/builders/Android%20Builder%20%28dbg%29/builds/64181/steps/check_licenses/logs/stdio

>
/b/build/slave/Android_Builder__dbg_/build/src/android_webview/tools/webview_licenses.py
scan
The following files contain a third-party license but are not in a listed
third-party directory and are not whitelisted. You must add the following files
to the whitelist.
chrome/common/extensions/docs/server2/gitiles_file_system.py
chrome/common/extensions/docs/server2/gitiles_file_system_test.py
<
/b/build/slave/Android_Builder__dbg_/build/src/android_webview/tools/webview_licenses.py
scan
ERROR: process exited with code 2

> Docserver: Introduce GitilesFileSystem
> 
> BUG=404239
> NOTRY=True
> 
> Review URL: https://codereview.chromium.org/470733002

TBR=ahernandez.miralles@gmail.com

Review URL: https://codereview.chromium.org/480573004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@290366 0039d316-1c4b-4281-b951-d872f2087c98