Revert "[EoS] Enable re-scrolling on back button."
This reverts commit bcdbfd512e036c7627a7a01b2085d4e65c9ba506.

Reason for revert: Broke beta build:

FAILED: gen/chrome/android/chrome_test_java.javac.jar gen/chrome/android/chrome_test_java.javac.jar.info 
python ../../build/android/gyp/javac.py --depfile=gen/chrome/android/chrome_test_java__compile_java.d --generated-dir=gen/chrome/android/chrome_test_java/generated_java --jar-path=gen/chrome/android/chrome_test_java.javac.jar --java-srcjars=\[\] --java-version=1.8 --full-classpath=@FileArg\(gen/chrome/android/chrome_test_java.build_config:deps_info:javac_full_classpath\) --interface-classpath=@FileArg\(gen/chrome/android/chrome_test_java.build_config:deps_info:javac_full_interface_classpath\) --processorpath=@FileArg\(gen/chrome/android/chrome_test_java.build_config:javac:processor_classpath\) --processors=@FileArg\(gen/chrome/android/chrome_test_java.build_config:javac:processor_classes\) --java-srcjars=@FileArg\(gen/chrome/android/chrome_test_java.build_config:deps_info:owned_resource_srcjars\) --bootclasspath=@FileArg\(gen/chrome/android/chrome_test_java.build_config:android:sdk_interface_jars\) --chromium-code=1 @gen/chrome/android/chrome_test_java.sources
Traceback (most recent call last):
  File "../../build/android/gyp/javac.py", line 638, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/javac.py", line 634, in main
    add_pydeps=False)
  File "/b/build/slave/beta-arm_64/build/src/build/android/gyp/util/build_utils.py", line 642, in CallAndWriteDepfileIfStale
    pass_changes=True)
  File "/b/build/slave/beta-arm_64/build/src/build/android/gyp/util/md5_check.py", line 87, in CallAndRecordIfStale
    function(*args)
  File "/b/build/slave/beta-arm_64/build/src/build/android/gyp/util/build_utils.py", line 627, in on_stale_md5
    function(*args)
  File "../../build/android/gyp/javac.py", line 626, in <lambda>
    classpath_inputs, classpath),
  File "../../build/android/gyp/javac.py", line 398, in _OnStaleMd5
    javac_generated_sources)
  File "../../build/android/gyp/javac.py", line 249, in _CreateInfoFile
    'Chromium java files must only have one class: {}'.format(source))
AssertionError: Chromium java files must only have one class: ../../chrome/android/javatests/src/org/chromium/chrome/browser/explore_sites/ExploreSitesPageTest.java

https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm_64/builds/15631
https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm_64/builds/15631/steps/Build%20Non-Channel%20Targets/logs/stdio

Original change's description:
> [EoS] Enable re-scrolling on back button.
> 
> This utilizes LinearLayoutManager#onSaveInstanceState to provide a
> parcelable.  This is stashed on the NavigationEntry (which is OK since it
> is not persisted in any way.)
> 
> Bug: 913012
> Change-Id: I903ef6440d1ef8e3d65d2e3764c2da35201b8b18
> Reviewed-on: https://chromium-review.googlesource.com/c/1362198
> Commit-Queue: Justin DeWitt <dewittj@chromium.org>
> Reviewed-by: Cathy Li <chili@chromium.org>
> Reviewed-by: Theresa <twellington@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#614608}(cherry picked from commit 2a94ae3b82c0e840d2eff0a21edb3cc591700f3c)
> Reviewed-on: https://chromium-review.googlesource.com/c/1369639
> Reviewed-by: Justin DeWitt <dewittj@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3626@{#204}
> Cr-Branched-From: d897fb137fbaaa9355c0c93124cc048824eb1e65-refs/heads/master@{#612437}

TBR=dewittj@chromium.org

Change-Id: I354bc0e42d3724154a69732218c9f1b98c418130
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 913012
Reviewed-on: https://chromium-review.googlesource.com/c/1371205
Reviewed-by: Justin DeWitt <dewittj@chromium.org>
Cr-Commit-Position: refs/branch-heads/3626@{#247}
Cr-Branched-From: d897fb137fbaaa9355c0c93124cc048824eb1e65-refs/heads/master@{#612437}