Revert "[merge m58] [Sync] Refactor ModelSafeWorker::DoWorkAndWaitUntilDone() to avoid code duplication."
This reverts commit 806a3f0007912ce4fb547cb2554860b6c23d4acb.

Breaks Android build:
../../components/sync/engine/model_safe_worker_unittest.cc:36:54: error:
no matching function for call to
'base::TestSimpleTaskRunner::PostTask(tracked_objects::Location,
std::__ndk1::remove_reference<base::Callback<void(),
(base::internal::CopyMode)0, (base::internal::RepeatMode)0>&>::type)'
     task_runner_->PostTask(FROM_HERE, std::move(work));

Cr-Commit-Position: refs/branch-heads/3029@{#711}
Cr-Branched-From: 939b32ee5ba05c396eef3fd992822fcca9a2e262-refs/heads/master@{#454471}