Revert of Copy some x509_certificate_model_nss functions to src/chromeos (patchset #4 id:80001 of https://codereview.chromium.org/2871993005/ )
Reason for revert:
Breaks the Linux ChromiumOS Builder (dbg)
Failure to link:
FAILED: chromeos_unittests
python "../../build/toolchain/gcc_link_wrapper.py" --output="./chromeos_unittests" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -pthread -Werror -Wl,--gdb-index --sysroot=../../build/linux/debian_jessie_amd64-sysroot -L/b/c/b/linux_chromeos/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -L/b/c/b/linux_chromeos/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/b/c/b/linux_chromeos/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -Wl,--export-dynamic -o "./chromeos_unittests" -Wl,--start-group @"./chromeos_unittests.rsp" ./libonc.so ./libproxy_config.so ./libcrcrypto.so ./libnet.so ./liburl.so ./libprotobuf_lite.so ./libchromeos.so ./libdbus.so ./libbase.so ./libpolicy_proto.so ./libboringssl.so ./libbase_i18n.so ./libicui18n.so ./libicuuc.so ./libnet_with_v8.so ./libprefs.so -Wl,--end-group   -ldl -lrt -ldbus-1 -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0
../../chromeos/network/certificate_helper_unittest.cc:19: error: undefined reference to 'chromeos::certificate::GetCertNameOrNickname(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:25: error: undefined reference to 'chromeos::certificate::GetCertAsciiNameOrNickname(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:27: error: undefined reference to 'chromeos::certificate::GetCertNameOrNickname(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:34: error: undefined reference to 'chromeos::certificate::GetCertNameOrNickname(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:43: error: undefined reference to 'chromeos::certificate::GetCertType(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:56: error: undefined reference to 'chromeos::certificate::GetCertType(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:68: error: undefined reference to 'chromeos::certificate::GetCertType(CERTCertificateStr*)'
../../chromeos/network/certificate_helper_unittest.cc:80: error: undefined reference to 'chromeos::certificate::GetCertType(CERTCertificateStr*)'

Original issue's description:
> Copy some x509_certificate_model_nss functions to src/chromeos
>
> Currently the Chrome OS network configuration UI is in src/chrome.
>
> We want to move this to Settings UI which uses the networkingPrivate
> extension API which is implemented in src/chromeos.
>
> For network configuration we need to provide a list of available
> certificates, including their display names, so we will need to
> duplicate much of the logic in CertLibrary.
>
> This is some initial cleanup work which removes the CertLibrary
> dependency on chrome/common/net/x509_certificate_model_nss.cc
> (which in turn depends on chrome/third_party/mozilla_security_manager
> and contains significantly more code than CertLibrary needs and
> would be difficult to migrate out of src/chrome).
>
> It also removes some unnecessary src/chrome dependencies, and modifies
> onc_certificate_importer_impl_unittest.cc to use the new helper method
> instead of its own copied version of GetCertType.
>
> BUG=380937
>
> Review-Url: https://codereview.chromium.org/2871993005
> Cr-Commit-Position: refs/heads/master@{#472488}
> Committed: https://chromium.googlesource.com/chromium/src/+/cacb41c8337950175840b754a368cec5c9632b8a

TBR=pmarko@chromium.org,mattm@chromium.org,tbarzic@chromium.org,emaxx@chromium.org,stevenjb@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=380937

Review-Url: https://codereview.chromium.org/2886213002
Cr-Commit-Position: refs/heads/master@{#472490}