CallSetupStateTracker: Rename CallSetupState() to GetCallSetupState()
GCC is stricter than clang when it comes to class members' names and how
they can change the meaning of a previously existing symbol with the same
name:

    In file included from ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker_unittest.cc:5:
    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker.h:102:35: error: declaration of ‘blink::CallSetupState blink::CallSetupStateTracker::CallSetupState() const’ [-fpermissive]
       CallSetupState CallSetupState() const;
                                       ^~~~~
    ../../third_party/blink/renderer/modules/peerconnection/call_setup_state_tracker.h:79:12: error: changes meaning of ‘CallSetupState’ from ‘enum class blink::CallSetupState’ [-fpermissive]
     enum class CallSetupState {
                ^~~~~~~~~~~~~~

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84709 contains a longer
explanation, but essentially having a |CallSetupState()| method can change
the meaning of references to the |CallSetupState| enum in the code depending
on where it is declared, which contradicts the C++ standard.

Fix it by renaming the method to |GetCallSetupState()| after commit
7b1a3d2d1 ("CallSetupStateTracker::CallSetupState() added").

Bug: 819294
Change-Id: I5660c7c39d107343567452a5575205090c23cae8
Reviewed-on: https://chromium-review.googlesource.com/c/1352354
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#611597}