Fix Textfield::SetStyle call from 185925
http://crrev.com/185925 broke compile, it just needs to call SetStyle on textfield_.
OmniboxViewViews itself was made to be a Views::Textfield after the branch was cut, but before the fi was landed.
http://master.chrome.corp.google.com:8011/builders/cros%20beta/builds/1739/steps/compile/logs/stdio
  CXX(target) out/Release/obj.target/browser_ui/chrome/browser/ui/views/omnibox/omnibox_view_views.o
chrome/browser/ui/views/omnibox/omnibox_view_views.cc: In member function ‘virtual void OmniboxViewViews::EmphasizeURLComponents()’:
chrome/browser/ui/views/omnibox/omnibox_view_views.cc:931: error: ‘SetStyle’ was not declared in this scope
make: *** [out/Release/obj.target/browser_ui/chrome/browser/ui/views/omnibox/omnibox_view_views.o] Error 1

> Merge 184322
> > Fix Views Omnibox diagonal strike styling.
> > 
> > Clear the diagonal strike style (before potentially applying URL security styling).
> > 
> > This was a simple regression from my http://crrev.com/180067
> > OmniboxViewViews previously cleared the diagonal strike style in line 919 of:
> > https://chromiumcodereview.appspot.com/11535014/diff/57050/chrome/browser/ui/views/omnibox/omnibox_view_views.cc
> > ApplyURLStyle(textfield_, 0, text.length(), base_color, false);
> > My change still reset the overall textfield color, but not the diagonal strike style. 
> > 
> > BUG=177082
> > TEST=Get SSL error (https://cacert.org), new tab, switch back to SSL error tab; only scheme has a strike.
> > R=pkasting@chromium.org
> > 
> > Review URL: https://chromiumcodereview.appspot.com/12315027
> 
> TBR=msw@chromium.org
> Review URL: https://codereview.chromium.org/12374088

TBR=msw@chromium.org
Review URL: https://codereview.chromium.org/12379079

git-svn-id: svn://svn.chromium.org/chrome/branches/1410/src@185938 0039d316-1c4b-4281-b951-d872f2087c98