Revert "Roll clang 317263:318575."
This reverts commit cb2b13fb6670ed08c846bc90f0cbe894af344250.

Reason for revert: It broke the build due to an enhanced warning, e.g.
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/24153

../../third_party/ffmpeg/libavcodec/bitstream.c:169:5: error: if statement has empty body [-Werror,-Wempty-body]
    ff_dlog(NULL, "new table index=%d size=%d\n", table_index, table_size);
    ^
../../third_party/ffmpeg/libavutil/internal.h:276:80: note: expanded from macro 'ff_dlog'
#   define ff_dlog(ctx, ...) do { if (0) av_log(ctx, AV_LOG_DEBUG, __VA_ARGS__); } while (0)

I believe this is fixed in a later revision of Clang that our ToT bots had already picked up, which is why I didn't see it.

Original change's description:
> Roll clang 317263:318575.
> 
> Bug: 782281
> 
> Change-Id: Ifad82da68a7356bd6463fd9b944f796a5a3f798c
> Reviewed-on: https://chromium-review.googlesource.com/777640
> Reviewed-by: Peter Collingbourne <pcc@chromium.org>
> Commit-Queue: Hans Wennborg <hans@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#517719}

TBR=eugenis@chromium.org,hans@chromium.org,rnk@chromium.org,pcc@chromium.org

Change-Id: I922f3b1f30b7119fa17d257a1ab29339ac8576ee
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 782281
Reviewed-on: https://chromium-review.googlesource.com/778281
Reviewed-by: Hans Wennborg <hans@chromium.org>
Commit-Queue: Hans Wennborg <hans@chromium.org>
Cr-Commit-Position: refs/heads/master@{#517720}