Revert "Roll closure compiler to v20190106."
This reverts commit 2c61ac8628a0888a8187e962dc980fbe9649b922.

Reason for revert: Breaks compile because of error in pending.js

[21256/69315] ACTION //mojo/public/js:bindings_lite(//build/toolchain/linux:clang_x64)
FAILED: gen/mojo/public/js/mojo_bindings_lite.js 
python ../../third_party/closure_compiler/js_binary.py --compiler ../../third_party/closure_compiler/compiler/compiler.jar --output gen/mojo/public/js/mojo_bindings_lite.js --deps gen/mojo/public/js/bindings_lite_sources.js_library --sources ../../mojo/public/js/bindings_lite.js --flags jscomp_error=accessControls jscomp_error=ambiguousFunctionDecl jscomp_error=checkTypes jscomp_error=checkVars jscomp_error=constantProperty jscomp_error=deprecated jscomp_error=externsValidation jscomp_error=globalThis jscomp_error=invalidCasts jscomp_error=missingProperties jscomp_error=missingReturn jscomp_error=nonStandardJsDocs jscomp_error=suspiciousCode jscomp_error=undefinedNames jscomp_error=undefinedVars jscomp_error=unknownDefines jscomp_error=uselessCode jscomp_error=visibility compilation_level=ADVANCED_OPTIMIZATIONS language_in=ECMASCRIPT_2017 language_out=ECMASCRIPT5_STRICT generate_exports --externs ../../third_party/closure_compiler/externs/chrome.js ../../third_party/closure_compiler/externs/polymer-1.0.js ../../third_party/closure_compiler/externs/mojo_core.js ../../third_party/closure_compiler/externs/pending.js
../../third_party/closure_compiler/externs/pending.js:120: ERROR - Variable Clipboard declared more than once. First occurrence: externs.zip//w3c_clipboard.js
function Clipboard() {}
         ^^^^^^^^^

1 error(s), 0 warning(s)


See https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-rel/15802


Original change's description:
> Roll closure compiler to v20190106.
> 
> chrome.js: 7ef3422e1e87480d560247d75fee181b4cac24d9 -> 816824e445eb7ccc97becd07bdaf638d71b2e543
> chrome_extensions.js: 929b2621980a8e5c3ea373f40f6e92c4a56d51be -> 2837b8bb87e537debd24fa649c18426fba905457
> polymer-1.0.js: 203ab5d7394ad4662eed051f28f6fd21404531b7 -> 2ad6ea7c43f23021245eeefc60cd476676a0e933
> 
> Bug: 922671
> Change-Id: Ie970d6e8f8b38a730bb30351f938a6f219037a1b
> Reviewed-on: https://chromium-review.googlesource.com/c/1414350
> Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
> Reviewed-by: calamity <calamity@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#623809}

TBR=calamity@chromium.org,dpapad@chromium.org

Change-Id: I80058e72fa3b9273d8cc949d5343b2ecad56c7fd
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 922671
Reviewed-on: https://chromium-review.googlesource.com/c/1418731
Reviewed-by: Ian Clelland <iclelland@chromium.org>
Commit-Queue: Ian Clelland <iclelland@chromium.org>
Auto-Submit: Ian Clelland <iclelland@chromium.org>
Cr-Commit-Position: refs/heads/master@{#623818}