Treat unknown accounts as auth errors in tests
We have multiple flaky tests that complain with:
java.lang.IllegalArgumentException: Can not find AccountHolder for account Account {name=test@gmail.com, type=com.google}
    at org.chromium.components.signin.test.util.FakeAccountManagerDelegate.getAccountHolder(FakeAccountManagerDelegate.java:341)
    at org.chromium.components.signin.test.util.FakeAccountManagerDelegate.getAuthToken(FakeAccountManagerDelegate.java:259)
    at org.chromium.components.signin.AccountManagerFacade$3.run(AccountManagerFacade.java:492)
    at org.chromium.components.signin.AccountManagerFacade$3.run(AccountManagerFacade.java:489)
    at org.chromium.components.signin.AccountManagerFacade$ConnectionRetry$1.doInBackground(AccountManagerFacade.java:829)
    at org.chromium.base.task.AsyncTask$1.call(AsyncTask.java:99)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 3 more

One hypothesis is that GetAccountHolder() fails during teardown of the
test. Hence, let's treat it as auth error such that
AccountManagerFacade.getAuthToken() treats it as a regular failed
attempt (but doesn't necessarily make the test fail).

Bug: 879246
Change-Id: I47c69af1af2579ec70ece468e6701f67ef065992
Reviewed-on: https://chromium-review.googlesource.com/c/1264678
Reviewed-by: Boris Sazonov <bsazonov@chromium.org>
Commit-Queue: Mikel Astiz <mastiz@chromium.org>
Cr-Commit-Position: refs/heads/master@{#597586}