Revert of DEPS: Update leveldatabase from 1.18 to 1.20. (patchset #3 id:60001 of https://codereview.chromium.org/2727693004/ )
Reason for revert:
Looks like this broke the Windows builders. Not sure how it passed CQ:

https://build.chromium.org/p/chromium/builders/Win/builds/52433

FAILED: obj/third_party/leveldatabase/leveldb_cache_test/cache_test.obj
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/third_party/leveldatabase/leveldb_cache_test/cache_test.obj.rsp /c ../../third_party/leveldatabase/src/util/cache_test.cc /Foobj/third_party/leveldatabase/leveldb_cache_test/cache_test.obj /Fd"obj/third_party/leveldatabase/leveldb_cache_test_cc.pdb"
c:\b\c\b\win_archive\src\third_party\leveldatabase\src\util\cache_test.cc(167): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_archive\src\third_party\leveldatabase\src\util\cache_test.cc(167): warning C4018: '<': signed/unsigned mismatch
c:\b\c\b\win_archive\src\third_party\leveldatabase\src\util\cache_test.cc(171): warning C4018: '<': signed/unsigned mismatch

Original issue's description:
> DEPS: Update leveldatabase from 1.18 to 1.20.
>
> This speeds up CRC32C computation from ~900MB/s to ~4GB/s on computers
> with modern Intel CPUs. Snappy decompression runs at around 4GB/s, so
> CRC32C is a limiting factor when reading large blocks, which can happen
> when we store large values.
>
> BUG=
>
> Review-Url: https://codereview.chromium.org/2727693004
> Cr-Commit-Position: refs/heads/master@{#454154}
> Committed: https://chromium.googlesource.com/chromium/src/+/c0182b5f45e7161cad9d586b75b66653575f46ce

TBR=cmumford@chromium.org,pwnall@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2723373002
Cr-Commit-Position: refs/heads/master@{#454160}