Workaround for MSVC compile error
This is workaround for MSVC compile error.
../../base/task_scheduler/task_tracker.cc(458): error C2440: 'initializing': cannot convert from 'base::HistogramBase *const (*)[2]' to 'base::HistogramBase *const (*&)[2]'

This has been happening on
https://ci.chromium.org/buildbot/chromium.fyi/WinMSVC64%20Goma%20Canary/6721

Change-Id: I64401b69a4ad2e1f9ea4716e127f26b0de662909
Reviewed-on: https://chromium-review.googlesource.com/1084131
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/master@{#563995}