Revert of Don't use the manifest brand color when a PWA is in immersive fullscreen. (patchset #1 id:1 of https://codereview.chromium.org/2900593003/ )
Reason for revert:
Breaks build

../../chrome/android/java/src/org/chromium/chrome/browser/webapps/WebappActivity.java:621: error: cannot find symbol
        if (mBrandColor != null && mWebappInfo.displayMode() != WebDisplayMode.FULLSCREEN) {

Original issue's description:
> Don't use the manifest brand color when a PWA is in immersive fullscreen.
>
> When in display: fullscreen, the status and navigation bars on Android
> are hidden, and can be swiped in by users if desired. The bars also
> appear if the on-screen keyboard is triggered. However, the bars
> sometimes appear as completely transparent, which hurts their usability.
>
> This CL explicitly sets the status bar color to black if a PWA is launched
> in display: fullscreen, and ignores the brand color specified in the web
> app manifest. This ensures that the status and navigation bars always
> have a solid black background and do not appear as transparent. Since
> PWAs that are open in display: fullscreen have the bars hidden most of
> the time, having a black color does not overly affect the native fit and
> feel too much.
>
> BUG=714704,716686
>
> Review-Url: https://codereview.chromium.org/2871103002
> Cr-Original-Commit-Position: refs/heads/master@{#470762}
> Review-Url: https://codereview.chromium.org/2900593003 .
> Cr-Commit-Position: refs/branch-heads/3071@{#646}
> Cr-Branched-From: a106f0abbf69dad349d4aaf4bcc4f5d376dd2377-refs/heads/master@{#464641}
> Committed: https://chromium.googlesource.com/chromium/src/+/8fc052bc58d3adbc8c6f6e13109da6e733f8ee20

TBR=dominickn@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=714704,716686

Review-Url: https://codereview.chromium.org/2893413002
Cr-Commit-Position: refs/branch-heads/3071@{#657}
Cr-Branched-From: a106f0abbf69dad349d4aaf4bcc4f5d376dd2377-refs/heads/master@{#464641}