Pass --smoke-test-mode to merge script.
I put this argument in the wrong place in
https://chromium-review.googlesource.com/c/chromium/src/+/1428090
so it applied to the test itself
rather than to the merge script. This could have caused bad data to start
being uploaded to the dashboard, however, thankfully the merge script failed:

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8923500104781854128/+/steps/components_perftests_on_Android_device_Nexus_5X__retry_with_patch_/0/logs/Merge_script_log/0
Error while uploading chartjson data: Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/tools/perf/core/results_dashboard.py", line 457, in _SendResultsJson
    urllib2.urlopen(req)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/b/s/w/ir/cipd_bin_packages/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

I didn't realize that the merge script failed because the bot stayed green:
https://ci.chromium.org/p/chromium/builders/luci.chromium.try/android-marshmallow-arm64-rel/175763A

TBR=jbudorick@chromium.org

Bug: 924351
Change-Id: I33da2cadb097c08d9ca20affdeb771f8c9561bec
Reviewed-on: https://chromium-review.googlesource.com/c/1435904
Reviewed-by: Caleb Rouleau <crouleau@chromium.org>
Reviewed-by: John Budorick <jbudorick@chromium.org>
Commit-Queue: Caleb Rouleau <crouleau@chromium.org>
Cr-Commit-Position: refs/heads/master@{#625962}