Revert "[webauthn] Don't terminate operations early that return NotAllowedError."
This reverts commit fefcfdfc9de7e7e9040ed98a99b21544a4f8bbbd.

Reason for revert:

WinMSVC64(dbg) bot error:
https://ci.chromium.org/buildbot/chromium.win/WinMSVC64%20(dbg)/2965

c:\b\c\b\win\src\content\browser\webauth\authenticator_impl.cc(393) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win\src\content\browser\webauth\authenticator_impl.cc(393) : warning C4702: unreachable code





Original change's description:
> [webauthn] Don't terminate operations early that return NotAllowedError.
> 
> NotAllowedError responses should not be returned until after the
> timer has expired in order to prevent a leak of possibly-identifying
> user information.
> 
> See https://w3c.github.io/webauthn/#createCredential step 21.
> 
> Bug: 809104
> Change-Id: I3655f4c9cac29dc29c68c234c2e0b8ea00f1c5c2
> Reviewed-on: https://chromium-review.googlesource.com/912149
> Commit-Queue: Kim Paulhamus <kpaulhamus@chromium.org>
> Reviewed-by: Balazs Engedy <engedy@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#537229}

TBR=engedy@chromium.org,kpaulhamus@chromium.org

Change-Id: I022d8586c26a9201c5d80a025b2a954cca3fe5d4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 809104
Reviewed-on: https://chromium-review.googlesource.com/923223
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#537232}