Revert of Update linux sysroot from Wheezy to Jessie (patchset #3 id:40001 of https://codereview.chromium.org/2748183005/ )
Reason for revert:
Breaks the Official Linux build. Expected deps aren't matching up:

[30924/30936] ACTION //chrome/installer/linux:stable_rpm(//build/toolchain/linux:clang_x64)
FAILED: google-chrome-stable_59.0.3050.0-1.x86_64.rpm
python ../../chrome/installer/linux/flock_make_package.py linux_package.lock installer/rpm/build.sh -o . -b . -a x64 -c stable -d google_chrome
Staging common install files in '/tmp/rpm.build.PQ88Wk'...
Staging RPM install files in '/tmp/rpm.build.PQ88Wk'...
Packaging x86_64...
--- /b/c/b/Google_Chrome_Linux_x64/src/out/Release/installer/rpm/expected_deps_x86_64	2017-03-23 06:48:22.885425473 -0700
+++ /dev/fd/63	2017-03-23 08:04:33.320136041 -0700
@@ -15,7 +15,9 @@
 libasound.so.2()(64bit)
 libatk-1.0.so.0()(64bit)
 libc.so.6()(64bit)
+libc.so.6(GLIBC_2.11)(64bit)
 libc.so.6(GLIBC_2.14)(64bit)
+libc.so.6(GLIBC_2.15)(64bit)
 libc.so.6(GLIBC_2.2.5)(64bit)
 libc.so.6(GLIBC_2.3)(64bit)
 libc.so.6(GLIBC_2.3.2)(64bit)

ERROR: Shared library dependencies changed!
If this is intentional, please update:
chrome/installer/linux/rpm/expected_deps_i386
chrome/installer/linux/rpm/expected_deps_x86_64

[30925/30936] ACTION //chrome/installer/linux:unstable_deb(//build/toolchain/linux:clang_x64)
FAILED: google-chrome-unstable_59.0.3050.0-1_amd64.deb
python ../../chrome/installer/linux/flock_make_package.py linux_package.lock installer/debian/build.sh -o . -b . -a x64 -c unstable -d google_chrome -s /b/c/b/Google_Chrome_Linux_x64/src/build/linux/debian_jessie_amd64-sysroot
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory
--- /b/c/b/Google_Chrome_Linux_x64/src/out/Release/installer/debian/expected_deps_x64_jessie	2017-03-23 06:48:22.885425473 -0700
+++ actual	2017-03-23 08:04:37.504250895 -0700
@@ -1,17 +1,17 @@
 gconf-service
 libasound2 (>= 1.0.16)
 libatk1.0-0 (>= 1.12.4)
-libc6 (>= 2.14)
+libc6 (>= 2.15)
 libcairo2 (>= 1.6.0)
 libcups2 (>= 1.4.0)
-libdbus-1-3 (>= 1.2.14)
+libdbus-1-3 (>= 1.1.4)
 libexpat1 (>= 2.0.1)
 libfontconfig1 (>= 2.11)
-libfreetype6 (>= 2.4.2)
+libfreetype6 (>= 2.3.9)
 libgcc1 (>= 1:4.1.1)
 libgconf-2-4 (>= 3.2.5)
 libgdk-pixbuf2.0-0 (>= 2.22.0)
-libglib2.0-0 (>= 2.31.8)
+libglib2.0-0 (>= 2.28.0)
 libgtk-3-0 (>= 3.3.16)
 libnspr4 (>= 2:4.9-2~)
 libnss3 (>= 2:3.13.4-2~)

ERROR: Shared library dependencies changed!
If this is intentional, please update:
chrome/installer/linux/debian/expected_deps_ia32_jessie
chrome/installer/linux/debian/expected_deps_ia32_wheezy
chrome/installer/linux/debian/expected_deps_x64_jessie
chrome/installer/linux/debian/expected_deps_x64_wheezy

Original issue's description:
> Update linux sysroot from Wheezy to Jessie
>
> This is an attempt to reland a change that was attempted
> several times already.  It now includes changes to the
> linux packaging expectations which previously caused
> failed on the official bots.
>
> TESTED=ninja linux_packages_all
> BUG=701894
>
> Review-Url: https://codereview.chromium.org/2748183005
> Cr-Commit-Position: refs/heads/master@{#459062}
> Committed: https://chromium.googlesource.com/chromium/src/+/94c4fa81c45284d0fe1e5616f52fcad56745077b

TBR=thestig@chromium.org,thomasanderson@chromium.org,dpranke@chromium.org,thakis@chromium.org,sbc@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=701894

Review-Url: https://codereview.chromium.org/2776503002
Cr-Commit-Position: refs/heads/master@{#459128}