Revert "[Feed] Add pagination and ui config params."
This reverts commit aff3df13ce885fc145e8c23ea57e68e26554b763.

Reason for revert: Fails to compile

../../chrome/android/feed/core/java/src/org/chromium/chrome/browser/feed/FeedConfiguration.java:213: error: cannot find symbol
                .put(ConfigKey.USE_SECONDARY_PAGE_REQUEST,
                              ^
  symbol:   variable USE_SECONDARY_PAGE_REQUEST
  location: @interface ConfigKey
1 error

Original change's description:
> [Feed] Add pagination and ui config params.
> 
> Bug: 928772
> Change-Id: I8d939e8b6803c4d67b4cc24f19e47b695f84400e
> Reviewed-on: https://chromium-review.googlesource.com/c/1460073
> Commit-Queue: Sky Malice <skym@chromium.org>
> Auto-Submit: Sky Malice <skym@chromium.org>
> Reviewed-by: Gang Wu <gangwu@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#630384}(cherry picked from commit eb2bb5a4cde699da9a9688d26cb49304d54d84aa)
> Reviewed-on: https://chromium-review.googlesource.com/c/1473825
> Reviewed-by: Sky Malice <skym@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3683@{#433}
> Cr-Branched-From: e51029943e0a38dd794b73caaf6373d5496ae783-refs/heads/master@{#625896}

TBR=skym@chromium.org

Change-Id: I5733d2c03a3f59883fce18d36a88ff68134dee9f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 928772
Reviewed-on: https://chromium-review.googlesource.com/c/1474250
Reviewed-by: Sky Malice <skym@chromium.org>
Cr-Commit-Position: refs/branch-heads/3683@{#434}
Cr-Branched-From: e51029943e0a38dd794b73caaf6373d5496ae783-refs/heads/master@{#625896}