Revert of Use TaskScheduler instead of blocking pool in version_updater_win.cc. (patchset #2 id:20001 of https://codereview.chromium.org/2672073002/ )
Reason for revert:
Broke compilation on Windows:
[31042/38338] CXX obj/chrome/browser/ui/ui_2/version_updater_win.obj
FAILED: obj/chrome/browser/ui/ui_2/version_updater_win.obj
ninja -t msvc -e environment.x86 -- C:\b\c\cipd\goma/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/chrome/browser/ui/ui_2/version_updater_win.obj.rsp /c ../../chrome/browser/ui/webui/help/version_updater_win.cc /Foobj/chrome/browser/ui/ui_2/version_updater_win.obj /Fd"obj/chrome/browser/ui/ui_2_cc.pdb"
c:\b\c\b\win_chrome\src\chrome\browser\ui\webui\help\version_updater_win.cc(58): error C2451: conditional expression of type 'void' is illegal
c:\b\c\b\win_chrome\src\chrome\browser\ui\webui\help\version_updater_win.cc(58): note: Expressions of type void cannot be converted to other types

https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/14901

Original issue's description:
> Use TaskScheduler instead of blocking pool in version_updater_win.cc.
>
> The blocking pool is being deprecated in favor of TaskScheduler.
>
> BUG=667892
> R=bauerb@chromium.org
>
> Review-Url: https://codereview.chromium.org/2672073002
> Cr-Commit-Position: refs/heads/master@{#448245}
> Committed: https://chromium.googlesource.com/chromium/src/+/ff3a44b07550e95f7b6615afeb8b763ec9601ce0

TBR=bauerb@chromium.org,fdoray@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=667892

Review-Url: https://codereview.chromium.org/2678843002
Cr-Commit-Position: refs/heads/master@{#448252}