Revert "Early return SetScrollbarsHiddenIfOverlay when PLSA has disposed paint layer"
This reverts commit 09116943290bcaf6da2a387546b24a3a6de86b71.

Reason for revert: Fails to compile on m66 builders, see https://uberchromegw.corp.google.com/i/official.android/builders/official-arm/builds/3091/steps/Build%20Non-Channel%20Targets/logs/stdio

Error is "error: no member named 'SetScrollbarsHiddenIfOverlay' in 'blink::PaintLayerScrollableArea'" which seems a problem given that the fix is about this specific method.

Original change's description:
> Early return SetScrollbarsHiddenIfOverlay when PLSA has disposed paint layer
> 
> This crash is caused by query the page scrollbar theme settings after PLSA
> disposed paint layer. In this patch, we added a HasBeenDisposed check before
> query the page scrollbar theme settings to prevent the crash.
> 
> TBR=chaopeng@chromium.org
> 
> (cherry picked from commit 46e1ab3342800f9c971551b02e69001b7d9d8b98)
> 
> Bug: 828523,813520
> Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
> Change-Id: I9c47e4daf88c78aa178e3d355e764639580628a9
> Reviewed-on: https://chromium-review.googlesource.com/994337
> Reviewed-by: David Bokan <bokan@chromium.org>
> Reviewed-by: Rick Byers <rbyers@chromium.org>
> Commit-Queue: Jianpeng Chao <chaopeng@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#548181}
> Reviewed-on: https://chromium-review.googlesource.com/1003352
> Cr-Commit-Position: refs/branch-heads/3359@{#638}
> Cr-Branched-From: 66afc5e5d10127546cc4b98b9117aff588b5e66b-refs/heads/master@{#540276}

TBR=rbyers@chromium.org,bokan@chromium.org,chaopeng@chromium.org

Change-Id: I0458cfc4fd9413d13140edb75e14e71546c24792
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 828523, 813520
Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel;master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2
Reviewed-on: https://chromium-review.googlesource.com/1005081
Reviewed-by: Mounir Lamouri <mlamouri@chromium.org>
Cr-Commit-Position: refs/branch-heads/3359@{#646}
Cr-Branched-From: 66afc5e5d10127546cc4b98b9117aff588b5e66b-refs/heads/master@{#540276}