Build fix for vulkan_tests.
This CL fixes the following build breaks:

In file included from ../../gpu/vulkan/vulkan_swap_chain.cc:5:
../../gpu/vulkan/vulkan_swap_chain.h:41:5: error: use of undeclared identifier 'DCHECK_LT'
    DCHECK_LT(index, images_.size());
    ^
../../gpu/vulkan/vulkan_swap_chain.h:50:5: error: use of undeclared identifier 'DCHECK_LT'
    DCHECK_LT(current_image_, images_.size());
    ^

BUG=none
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel

Review-Url: https://codereview.chromium.org/2713083002
Cr-Commit-Position: refs/heads/master@{#454010}