Revert "[NTP::Articles::Cleanup] Use builders and mock fetcher in tests [3/3]."
This reverts commit 576d948ad41d11d97d7baaaadee420b985e55eb9.

Reason for revert: Compile error on Linux Trybot

Error message:

../../components/ntp_snippets/remote/remote_suggestions_provider_impl_unittest.cc:626:49: error: chosen constructor is explicit in copy-initialization
        kKeepPrefetchedContentSuggestions.name, {},
                                                ^~
../../build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/debug/map.h:75:16: note: explicit constructor declared here
      explicit map(const _Compare& __comp = _Compare(),
               ^
../../components/variations/variations_params_manager.h:64:49: note: passing argument to parameter 'param_values' here
      const std::map<std::string, std::string>& param_values,

Original change's description:
> [NTP::Articles::Cleanup] Use builders and mock fetcher in tests [3/3].
> 
> This CL rewrites the remaining of the tests to use new builders and mock
> fetcher. Also some tests are slightly improved, but larger issues are
> left out. This is the third and last CL in this series. As a result,
> multiple old helpers are removed.
> 
> Bug: 733129
> Change-Id: Idda4e5c8c39b9cf131a9dfba0568f4aa5321d67a
> Reviewed-on: https://chromium-review.googlesource.com/558926
> Reviewed-by: Jan Krcal <jkrcal@chromium.org>
> Commit-Queue: vitaliii <vitaliii@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#484265}

TBR=jkrcal@chromium.org,vitaliii@chromium.org

Change-Id: Ib9be4d4e244d7212c76628693b9f87ca85473b2d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 733129
Reviewed-on: https://chromium-review.googlesource.com/559569
Reviewed-by: vitaliii <vitaliii@chromium.org>
Commit-Queue: vitaliii <vitaliii@chromium.org>
Cr-Commit-Position: refs/heads/master@{#484270}