Revert "Extension API: Move easyUnlockPrivate API to be CrOS-only."
This reverts commit 878a6bb6de52ada7ae31116f934dfbb26a527750.

Reason for revert: Caused build error
https://ci.chromium.org/buildbot/chromium/Linux%20x64/59639

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium%2FLinux_x64%2F59639%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

In file included from ../../chrome/browser/extensions/api/easy_unlock_private/easy_unlock_private_crypto_delegate_stub.cc:6:
../../chrome/browser/extensions/api/easy_unlock_private/easy_unlock_private_crypto_delegate.h:12:10: fatal error: 'chrome/common/extensions/api/easy_unlock_private.h' file not found
#include "chrome/common/extensions/api/easy_unlock_private.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> Extension API: Move easyUnlockPrivate API to be CrOS-only.
> 
> This is true in practice and is the next step in making SmartLock
> CrOS-only.
> 
> Bug: 817115
> Test: Existing tests
> Change-Id: I38560b7d35859f65148a6a6cbbb9e4a66e7955a5
> Reviewed-on: https://chromium-review.googlesource.com/940538
> Reviewed-by: Karan Bhatia <karandeepb@chromium.org>
> Reviewed-by: Toni Barzic <tbarzic@chromium.org>
> Commit-Queue: James Hawkins <jhawkins@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#539965}

TBR=tbarzic@chromium.org,jhawkins@chromium.org,lazyboy@chromium.org,benwells@chromium.org,karandeepb@chromium.org

Change-Id: Ib5425ec7d3c9283a6fcb776a11c6a1a2f6b61efe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 817115
Reviewed-on: https://chromium-review.googlesource.com/942421
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#539969}