Reland of Disable swipe down to enter the tab switcher in Chrome Home. (patchset #1 id:1 of https://codereview.chromium.org/2761463004/ )
Reason for revert:
Since this affects entering the tab switcher on user gesture (and only if a chrome flag is turned on), I'm pretty sure this was not the underlying cause.

Most likely some transient issue that caused all the devices to go offline or be unreachable.

There was this in the logs that I got from jbudorick@
NoDevicesError: No devices attached.

Original issue's description:
> Revert of Disable swipe down to enter the tab switcher in Chrome Home. (patchset #1 id:1 of https://codereview.chromium.org/2755823004/ )
>
> Reason for revert:
> Possibly broke multiple tests on Android concerning e.g. opening tabs.
> https://build.chromium.org/p/chromium.linux/builders/Android%20Tests%20%28dbg%29/builds/40909
>
>
> Original issue's description:
> > Disable swipe down to enter the tab switcher in Chrome Home.
> >
> > BUG=
> >
> > Review-Url: https://codereview.chromium.org/2755823004
> > Cr-Commit-Position: refs/heads/master@{#457836}
> > Committed: https://chromium.googlesource.com/chromium/src/+/f3b96a7b630ef08149c29ffab26a70df8d54f6d8
>
> TBR=mdjones@chromium.org,tedchoc@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=
>
> Review-Url: https://codereview.chromium.org/2761463004
> Cr-Commit-Position: refs/heads/master@{#457889}
> Committed: https://chromium.googlesource.com/chromium/src/+/0e89702abe2235bfb1bc778444d2eb2f166567ad

TBR=mdjones@chromium.org,nektar@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2755273002
Cr-Commit-Position: refs/heads/master@{#457904}