Revert "WebUI Polymer 2 migration: Convert <dialog is=cr-dialog> to a <dialog> wrapper."
This reverts commit a5442982ebaeaeac309d5bea01a9127216a889eb.

Reason for revert: 
Causes browser_tests failing on chromium.chromiumos/linux-chromeos-dbg

failures:
CrSettingsAndroidAppsPageTest.All
CrSettingsFingerprintListTest.All

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.chromiumos%2Flinux-chromeos-dbg%2F5028%2F%2B%2Frecipes%2Fsteps%2Fbrowser_tests%2F0%2Flogs%2FCrSettingsAndroidAppsPageTest.All%2F0
AssertionError: expected undefined to be false
    at Function.assert.isFalse (file:///b/s/w/ir/third_party/chaijs/chai.js:2459:31)
    at assertFalse (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:862:17)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/android_apps_page_test.js:125:7)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (48)
[1113:1113:0403/172824.531829:ERROR:web_ui_test_handler.cc(82)] Test Errors: 1/9 tests had failed assertions.
[1113:1113:0403/172824.531924:ERROR:web_ui_browser_test.cc(475)] CONDITION FAILURE: encountered javascript console error(s):
[1113:1113:0403/172824.531950:ERROR:web_ui_browser_test.cc(477)] JS ERROR: '[1113:1113:0403/172824.017897:ERROR:CONSOLE(48)] "Mocha test failed: AndroidAppsPageTests SubPage Disable
AssertionError: expected undefined to be false
    at Function.assert.isFalse (file:///b/s/w/ir/third_party/chaijs/chai.js:2459:31)
    at assertFalse (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:862:17)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/android_apps_page_test.js:125:7)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (48)
'
[1113:1113:0403/172824.531980:ERROR:web_ui_browser_test.cc(479)] JS call assumed failed, because JS console error(s) found.
gen/chrome/test/data/webui/settings/cr_settings_browsertest-gen.cc:2866: Failure
Value of: RunJavascriptTestF( true, "CrSettingsAndroidAppsPageTest", "All")
  Actual: false
Expected: true


Original change's description:
> WebUI Polymer 2 migration: Convert <dialog is=cr-dialog> to a <dialog> wrapper.
> 
> Polymer2 does not support HTML element extensions, so all such elements need to
> be converted to wrappers.
> 
>  - Introduced a new --cr-dialog-native CSS mixin, such that users of <cr-dialog>
>    can still style the inner native <dialog>. Before, this was not necessary,
>    since <cr-dialog> itself was a <dialog>, and not a wrapper. Update all such
>    cases to use the mixin.
>  - Introduced a public getNative() method to expose the internal <dialog>, which
>    is necessary in a few cases (both tests and prod).
>  - Mirrored <dialog>'s |open| attribute such  that it updates synchronously as soon
>    a dialog is opened or closed. This matches the internal <dialog>'s behavior.
>  - Updated tests as necessary (and did a significant amount of manual sanity
>    checking).
> 
> Bug: 818279
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: I4fb35237d3ea3fa3dbb8ef4602036a4783f1e896
> Reviewed-on: https://chromium-review.googlesource.com/976394
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
> Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
> Reviewed-by: Scott Chen <scottchen@chromium.org>
> Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#547860}

TBR=stevenjb@chromium.org,dpapad@chromium.org,rbpotter@chromium.org,scottchen@chromium.org

Change-Id: If9454d64d28b600267dc8fa4a18151dce71fe722
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 818279
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Reviewed-on: https://chromium-review.googlesource.com/994439
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#548009}