Revert "media/gpu/test: Add test helper class to write video frames to file."
This reverts commit 024dbfcb347fe60d9ba64a40d6e951e895783bd3.

Reason for revert: Suspect compile failure on win32-rel bot
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/win32-rel/10126
../../media/gpu/test/video_frame_file_writer.cc(79,28):  error: no member named 'MakeAbsoluteFilePath' in namespace 'base'
    output_folder_ = base::MakeAbsoluteFilePath(
                     ~~~~~~^
../../media/gpu/test/video_frame_file_writer.cc(85,8):  error: use of undeclared identifier 'DirectoryExists'
  if (!DirectoryExists(output_folder_)) {
       ^
../../media/gpu/test/video_frame_file_writer.cc(86,11):  error: no type named 'CreateDirectoryW' in namespace 'base'
    base::CreateDirectory(output_folder_);
    ~~~~~~^
..\..\third_party\depot_tools\win_toolchain\vs_files\818a152b3f1da991c1725d85be19a0f27af6bab4\win_sdk\Include\10.0.17763.0\um\fileapi.h(73,26):  note: expanded from macro 'CreateDirectory'
#define CreateDirectory  CreateDirectoryW
...


Original change's description:
> media/gpu/test: Add test helper class to write video frames to file.
> 
> This helper provides more flexibility and improves code re-use. Currently only
> writing to png files is supported, but it's easy to expand the interface to
> writing raw files etc.
> 
> TEST=ran new VDA tests on nocturne
> 
> BUG=879065
> 
> Change-Id: I08ea462f98c9aba993ec7ef0b64d74fef11360fa
> Reviewed-on: https://chromium-review.googlesource.com/c/1420490
> Commit-Queue: David Staessens <dstaessens@chromium.org>
> Reviewed-by: Hirokazu Honda <hiroh@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#626007}

TBR=hiroh@chromium.org,dstaessens@chromium.org

Change-Id: I16328a9dbd1378887bcf97f561f5d9166e99a7c8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 879065
Reviewed-on: https://chromium-review.googlesource.com/c/1436284
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#626014}