Revert "[Ribbon] Add property API for descriptors so we can handle their CSSPropertyMetadata"
This reverts commit 54ed2d3d71238fd9b0605f03c7ac6f5b8c6cb793.

Reason for revert: 
Seems to fail compile failure:
FAILED: obj/third_party/WebKit/Source/core/core_generated/CSSPropertyAPI.o
gen/blink/core/css/properties/CSSPropertyAPI.cpp:245:33: error: unused variable 'base_api' [-Werror,-Wunused-const-variable]
static constexpr CSSPropertyAPI base_api;
                                ^
1 error generated.

Original change's description:
> [Ribbon] Add property API for descriptors so we can handle their CSSPropertyMetadata
> 
> Bug: 751373
> Change-Id: I89b116dd45393a5a1fe9329ea90864d97e77a7c1
> Reviewed-on: https://chromium-review.googlesource.com/603029
> Commit-Queue: meade_UTC10 <meade@chromium.org>
> Reviewed-by: meade_UTC10 <meade@chromium.org>
> Reviewed-by: Bugs Nash <bugsnash@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#492273}

TBR=rjwright@chromium.org,meade@chromium.org,bugsnash@chromium.org

Change-Id: Ia3ce3a9be9a70ccb95829a70cbeff31714ac86b7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 751373
Reviewed-on: https://chromium-review.googlesource.com/603037
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#492274}