Revert of [Merge to M58]cros: Replace "TPM" with "secure module" for machines without TPM. (patchset #1 id:1 of https://codereview.chromium.org/2871673002/ )
Reason for revert:
M58 build break.

 ../../components/login/secure_module_util_chromeos.cc -o obj/components/login/login/secure_module_util_chromeos.o
../../components/login/secure_module_util_chromeos.cc:43:25: error: no member named 'MayBlock' in namespace 'base'
      FROM_HERE, {base::MayBlock(), base::TaskPriority::BACKGROUND},

Original issue's description:
> [Merge to M58]cros: Replace "TPM" with "secure module" for machines without TPM.
>
> The new reef devices have a chip that is not a TPM so for these we do not want to display TPM strings. For now duplicate the strings since we need to merge to M58 & M59, but a follow up CL should use placeholders in the strings. There are two locations, adding supervised user and OOBE EULA screen.
>
> TEST=manual
> BUG=716671
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:closure_compilation
>
> Review-Url: https://codereview.chromium.org/2856683002
> Cr-Commit-Position: refs/heads/master@{#469826}
> (cherry picked from commit 6dfb54fcb774508b6679b8d83f0d935232b3a450)
>
> Review-Url: https://codereview.chromium.org/2871673002 .
> Cr-Commit-Position: refs/branch-heads/3029@{#816}
> Cr-Branched-From: 939b32ee5ba05c396eef3fd992822fcca9a2e262-refs/heads/master@{#454471}
> Committed: https://chromium.googlesource.com/chromium/src/+/cb8fbf78eefbcbf4843a4eaded90ce29d2fe5dad

TBR=sammiequon@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=716671

Review-Url: https://codereview.chromium.org/2867883002
Cr-Commit-Position: refs/branch-heads/3029@{#820}
Cr-Branched-From: 939b32ee5ba05c396eef3fd992822fcca9a2e262-refs/heads/master@{#454471}