Revert of Don't upload crash reports for cellular connection. (patchset #1 id:1 of https://codereview.chromium.org/1431313003/ )
Reason for revert:
I'm reverting this change because it broke the release branch. The branch is not compiling due to the missing declaration for UPLOAD_SUCCESS and UPLOAD_FAILURE constants.

Here's the compilation error message:

../chrome/android/java/src/org/chromium/chrome/browser/crash/MinidumpUploadCallable.java:112: error: cannot find symbol
            return success ? UPLOAD_SUCCESS : UPLOAD_FAILURE;
                             ^
  symbol:   variable UPLOAD_SUCCESS
  location: class MinidumpUploadCallable
../chrome/android/java/src/org/chromium/chrome/browser/crash/MinidumpUploadCallable.java:112: error: cannot find symbol
            return success ? UPLOAD_SUCCESS : UPLOAD_FAILURE;
                                              ^
  symbol:   variable UPLOAD_FAILURE
  location: class MinidumpUploadCallable
2 errors

Original issue's description:
> Don't upload crash reports for cellular connection.
>
> This only applies to clients who are in experimental group for enabling UMA log uploads on cellular connection by default.
>
> This is a precaution for not overwhelming users data plan.
>
> BUG=552066
>
> Review URL: https://codereview.chromium.org/1423483007
>
> Cr-Commit-Position: refs/heads/master@{#358654}
> (cherry picked from commit 5530fb8260611c02b6b231aba5add3fd25e593b7)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/5fbef022ad51dee7ff27b476f915a356d6a0ca69

TBR=jwd@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=552066

Review URL: https://codereview.chromium.org/1419113004

Cr-Commit-Position: refs/branch-heads/2526@{#372}
Cr-Branched-From: cb947c0153db0ec02a8abbcb3ca086d88bf6006f-refs/heads/master@{#352221}