Revert of Roll src/third_party/catapult/ 8ac279fd8..0adb6ef9b (1 commit). (patchset #1 id:1 of https://codereview.chromium.org/2477243003/ )
Reason for revert:
Failed compile on official.desktop.continuous for win trunk
https://bugs.chromium.org/p/chromium/issues/detail?id=662998

Link to Build:
-------------
https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20trunk/builds/49769

Link to Log Path:
------------------
https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20trunk/builds/49769/steps/compile/logs/stdio

Error log :

FAILED: net_unittests.exe net_unittests.exe.pdb
C:/b/depot_tools/python276_bin/python.exe ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /OUT:./net_unittests.exe /PDB:./net_unittests.exe.pdb @./net_unittests.exe.rsp
c:\b\build\slave\win_trunk\build\src\v8\src\heap\mark-compact.cc(1278) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information

scheib@ could you please look into this. thank you

Original issue's description:
> Roll src/third_party/catapult/ 8ac279fd8..0adb6ef9b (1 commit).
>
> https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+log/8ac279fd8db3..0adb6ef9b5dd
>
> $ git log 8ac279fd8..0adb6ef9b --date=short --no-merges --format='%ad %ae %s'
> 2016-11-07 nednguyen [Telemetry] Remove the logic of killing stray adb processes
>
> BUG=656224
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
>
> If the roll is causing failures, see:
> http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium#TOC-Failures-due-to-DEPS-rolls
>
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.android:android_optional_gpu_tests_rel
> TBR=catapult-sheriff@chromium.org
>
> Committed: https://crrev.com/4711d631a805e410531fbba09e9c69278b2d17c0
> Cr-Commit-Position: refs/heads/master@{#430279}

TBR=catapult-sheriff@chromium.org,catapult-deps-roller@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=656224

Review-Url: https://codereview.chromium.org/2484833002
Cr-Commit-Position: refs/heads/master@{#430328}