Remove variable shadowing in blink/input
In an effort to reduce or even ban variable shadowing, this renames
some variables to avoid such shadowing. I'm interested in prohibiting
shadowing because I think it might prevent potential jumbo problems.

The exact warning this avoids is:
third_party/blink/renderer/core/input/event_handler.cc:757:20: error: declaration shadows a local variable [-Werror,-Wshadow]
    HitTestRequest request(HitTestRequest::kReadOnly | HitTestRequest::kActive);
                   ^
third_party/blink/renderer/core/input/event_handler.cc:636:18: note: previous declaration is here
  HitTestRequest request(HitTestRequest::kActive);
                 ^
third_party/blink/renderer/core/input/event_handler.cc:772:22: error: declaration shadows a local variable [-Werror,-Wshadow]
      HitTestRequest request(HitTestRequest::kReadOnly |
                     ^
third_party/blink/renderer/core/input/event_handler.cc:636:18: note: previous declaration is here
  HitTestRequest request(HitTestRequest::kActive);
                 ^
third_party/blink/renderer/core/input/scroll_manager.cc:254:11: error: declaration shadows a local variable [-Werror,-Wshadow]
    Node* node = DOMNodeIds::NodeForId(scroll_chain.back());
          ^
third_party/blink/renderer/core/input/scroll_manager.cc:228:9: note: previous declaration is here
  Node* node = start_node;
        ^

Bug: 923510
Change-Id: I2bfd6993232654574a11dbfe7ded2b27555d931a
Reviewed-on: https://chromium-review.googlesource.com/c/1494877
Auto-Submit: Daniel Bratell <bratell@opera.com>
Reviewed-by: David Bokan <bokan@chromium.org>
Commit-Queue: Daniel Bratell <bratell@opera.com>
Cr-Commit-Position: refs/heads/master@{#637296}