Reland "[Merge M-73][PR][Android] Block payment UI from background tab"
This is a reland of 25fc2ca025934e177dde68e67dfe3670bde65f82

ToT patch landed in: https://crrev.com/c/1507125
First merged into M-73 release branch in: https://crrev.com/c/1508778
Reverted from M-73 release branch in: https://crrev.com/c/1511257
Reason for revert: Cannot find symbol getOverviewModeBehavior().
Change in reland: Removed getOverviewModeBehavior().

Original change's description:
> [Merge M-73][PR][Android] Block payment UI from background tab
>
> Before this patch, a background tab could show the payment sheet.
>
> This patch aborts payment if the web contents of the currently active
> tab are not the same as the web contents that invoked the PaymentRequest
> API.
>
> After this patch, Chrome rejects the PaymentRequest.show() with
> "AbortError: Request cancelled" if it was called from a tab that is not
> currently shown to the user.
>
> TBR=rouslan@chromium.org
>
> (cherry picked from commit 27309f38c3d3ce5f83b682b13cf98980ec8d9210)
>
> Bug: 939162
> Change-Id: Ia4e3eba7b882b5361185536e5b2b96edc80f5a11
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1507125
> Reviewed-by: Theresa <twellington@chromium.org>
> Commit-Queue: Rouslan Solomakhin <rouslan@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#638409}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1508778
> Reviewed-by: Rouslan Solomakhin <rouslan@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3683@{#775}
> Cr-Branched-From: e51029943e0a38dd794b73caaf6373d5496ae783-refs/heads/master@{#625896}

TBR=benmason@chromium.org

Bug: 939162, 939742
Change-Id: I9969cdff4236a8dbc66e447c1c80610ec5b273fe
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1511693
Reviewed-by: Rouslan Solomakhin <rouslan@chromium.org>
Cr-Commit-Position: refs/branch-heads/3683@{#786}
Cr-Branched-From: e51029943e0a38dd794b73caaf6373d5496ae783-refs/heads/master@{#625896}