cros: Add VIEWS_EXPORT to MenuSeparator
MenuSeparator is being reused in Ash, but to do this VIEWS_EXPORT
needs to be added to views::MenuSeparator. Else we have linker failures:

std::__1::allocator<char> > const&): error: undefined reference to
'vtable for views::MenuSeparator'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable
symbol may be undefined because the class is missing its key function

Bug: 861885
Change-Id: I787fe6bf1d62518d03e52007b792481251ae4174
Reviewed-on: https://chromium-review.googlesource.com/1129999
Reviewed-by: Michael Wasserman <msw@chromium.org>
Commit-Queue: Alex Newcomer <newcomer@chromium.org>
Cr-Commit-Position: refs/heads/master@{#573477}