Brush up LayoutSelectionTest
This patch updates the test harness so that error output is easy to catch.
Here is example:
[77636:25352:0704/182040.164:1516922546:ERROR:layout_selection_test.cc(120)]
case 2 failed.
case 4 failed.
422200DC BODY, state:Contain, NotInvalidate
42230010 RUBY, state:None, NotInvalidate
42234010 #text "foo", state:Start, ShouldInvalidate
42220340 RT, state:Contain, NotInvalidate
422340A0 #text "bar", state:End, ShouldInvalidate
../../third_party/blink/renderer/core/editing/layout_selection_test.cc(854): error: Value of: CheckResult()
  Actual: false
Expected: true
Stack trace:
,,,

Cq-Include-Trybots: luci.chromium.try:linux_layout_tests_layout_ng
Change-Id: I1f9a87f6c48b4b0b79be54ef4628e6742422bca2
Reviewed-on: https://chromium-review.googlesource.com/1125713
Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
Commit-Queue: Yoichi Osato <yoichio@chromium.org>
Cr-Commit-Position: refs/heads/master@{#572725}