[jumbo] avoid lookup conflict with extensions::features
This avoids the following jumbo build error:

./../../chrome/browser/extensions/api/content_settings/content_settings_api.cc:255:36: error: no member named 'kPermissionDelegation' in namespace 'extensions::features'; did you mean '::features::kPermissionDelegation'?

      base::FeatureList::IsEnabled(features::kPermissionDelegation)) {
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   ::features::kPermissionDelegation
../../chrome/common/chrome_features.h:301:28: note: '::features::kPermissionDelegation' declared here
extern const base::Feature kPermissionDelegation;
                           ^

Followup to https://chromium-review.googlesource.com/1173192

Change-Id: I6b6c39ed99f17a48bf7625aecf36ae3a23052ef0
Reviewed-on: https://chromium-review.googlesource.com/1193935
Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
Commit-Queue: Mostyn Bramley-Moore <mostynb@vewd.com>
Cr-Commit-Position: refs/heads/master@{#587635}