Revert "Remove unused device statistics"
This reverts commit dc6e43337fd8a150e009a281128dc0f262e12516.

Reason for revert:

This broke the Linux Chrome ChromeOS build:
https://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20ChromeOS/builds/39625

Specifically:
../../chrome/browser/chromeos/login/enrollment/auto_enrollment_controller.cc:96:21: error: no member named 'kFirmwareTypeKey' in namespace 'chromeos::system'

Original change's description:
> Remove unused device statistics
> 
> Delete mainfw_type and wpsw_boot. Fix alphabetic ordering of remaining
> statistics.
> 
> BUG=none
> 
> Change-Id: I8d7cb83bab87c6256cbe59b45084016e8025477f
> Reviewed-on: https://chromium-review.googlesource.com/677202
> Reviewed-by: Dan Erat <derat@chromium.org>
> Commit-Queue: Thiemo Nagel <tnagel@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#503447}

TBR=derat@chromium.org,tnagel@chromium.org

Change-Id: I80546a63928cf900db3529dddc2a90205fe02b5e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: none
Reviewed-on: https://chromium-review.googlesource.com/677224
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
Cr-Commit-Position: refs/heads/master@{#503448}