Revert of Add an experimental standalone content suggestions UI. (patchset #8 id:140001 of https://codereview.chromium.org/2593523005/ )
Reason for revert:
Speculative revert, likely broke:

https://uberchromegw.corp.google.com/i/chromium.linux/builders/Android%20Tests%20%28dbg%29/builds/38814

However, there appears to be logdog problems, so I'm not sure if we are getting realistic error messages.

E 1343.751s run_tests_on_device(07601d750ae534e5)  Error not bootstrapped. Failed to start logdog: Missing project [LOGDOG_STREAM_PROJECT]
Traceback (most recent call last):
  File "/b/s/w/irq8DwmG/build/android/pylib/android/logdog_logcat_monitor.py", line 28, in __init__
    self._stream_client = bootstrap.ButlerBootstrap.probe().stream_client()
  File "/b/s/w/irq8DwmG/tools/swarming_client/libs/logdog/bootstrap.py", line 48, in probe
    raise NotBootstrappedError('Missing project [%s]' % (cls._ENV_PROJECT,))
NotBootstrappedError: Missing project [LOGDOG_STREAM_PROJECT]

Original issue's description:
> Add an experimental standalone content suggestions UI.
>
> The UI is hidden behind a feature flag that enables a menu item (which
> uses innovative string compression techniques to avoid bloat due to
> i18n) to open the standalone content suggestions UI.
>
> While the activity and menu item are not meant to be shipped in an
> enabled state, this will allow iterating on a content suggestions UI
> outside of the NTP.
>
> Review-Url: https://codereview.chromium.org/2593523005
> Cr-Commit-Position: refs/heads/master@{#441980}
> Committed: https://chromium.googlesource.com/chromium/src/+/1b34593a53181b7f8a06a97206219c16486b33a1

TBR=mvanouwerkerk@chromium.org,dgn@chromium.org,bauerb@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2614023005
Cr-Commit-Position: refs/heads/master@{#442068}