Add //ui/snapshot to browser deps if aura is enabled.
When building chromium with use_aura=true, it is possible
that //ui/snapshot is not added as a dependency, resulting in build
errors like:
/usr/bin/ld.bfd: obj/chrome/browser/libbrowser.a
(native_desktop_media_list.o): undefined reference to symbol
'_ZN2ui31GrabWindowSnapshotAndScaleAsyncEPN4aura6WindowERKN3gfx...
This is because there is USE_AURA conditional code in
native_desktop_media_list.cc.

BUG=

Review-Url: https://codereview.chromium.org/2476003002
Cr-Commit-Position: refs/heads/master@{#431899}