Revert "[autofill] add iOS helpers to get aria-label and aria-description"
This reverts commit 95c8ebc6e5b760aa85692b012f448c4fa10d53d6.

Reason for revert: Breaks FillJsTest: https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/ios-webview/1004

JavaScript error: TypeError: __gCrWeb.fill.getAriaDescription is not a function.

Original change's description:
> [autofill] add iOS helpers to get aria-label and aria-description
> 
> This CL adds the getAriaLabel() and getAriaDescription() helper
> functions to the __GCrWeb.fill "namespace". These functions return
> the ARIA label and description strings associated with an element.
> 
> The ARIA Label is the text referenced by one or more containing element
> ids in the labelled elements aria-labelledby attribute, or the value
> of the element's aria-label attribute, with preference given to the
> aria-labelledby attribute. For example:
> 
>     <div id='foo-label'>Label for Foo</div>
>     <input name='foo' aria-labelledby='foo-label'>
>     <input name='bar' aria-label='Label for Bar'>
> 
> The aria-description is similar to aria-labelledby. For example:
> 
>     <div id='foo-description'>Long descriptive text for Foo</div>
>     <input name='foo' aria-describedby='foo-descrition'>
> 
> Bug: 896719
> Change-Id: I300b84298fc20e1b86474f60d08cdd1c9569036b
> Reviewed-on: https://chromium-review.googlesource.com/c/1325032
> Reviewed-by: Sebastien Seguin-Gagnon <sebsg@chromium.org>
> Reviewed-by: Moe Ahmadi <mahmadi@chromium.org>
> Commit-Queue: Roger McFarlane <rogerm@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#606534}

TBR=rogerm@chromium.org,sebsg@chromium.org,mahmadi@chromium.org

Change-Id: I00eb534e6639c829f6ed5b312406ce51ba2aa429
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 896719
Reviewed-on: https://chromium-review.googlesource.com/c/1329002
Reviewed-by: Patrik Höglund <phoglund@chromium.org>
Commit-Queue: Patrik Höglund <phoglund@chromium.org>
Cr-Commit-Position: refs/heads/master@{#606803}