Reland of Support for OpenType Font Variations on Windows (patchset #1 id:1 of https://codereview.chromium.org/2786263002/ )
Reason for revert:
The revert didn't help.

https://luci-milo.appspot.com/buildbot/chromium.linux/Linux%20Builder%20(dbg)(32)/65398

Original issue's description:
> Revert of Support for OpenType Font Variations on Windows (patchset #8 id:140001 of https://codereview.chromium.org/2780133002/ )
>
> Reason for revert:
> Compile failure on linux bot: https://uberchromegw.corp.google.com/i/chromium.linux/builders/Linux%20Builder%20%28dbg%29%2832%29/builds/65396
>
> [6410/39636] CXX obj/third_party/pdfium/formfiller/cffl_interactiveformfiller.o
> FAILED: obj/third_party/pdfium/formfiller/cffl_interactiveformfiller.o
> /b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/pdfium/formfiller/cffl_interactiveformfiller.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"298539-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DV8_DEPRECATION_WARNINGS -D_FX_CPU_=_FX_X86_ -DOPJ_STATIC -DPNG_PREFIX -DPNG_USE_READ_MACROS -DPDF_ENABLE_V8 -DPDFIUM_PRINT_TEXT_WITH_GDI -I../.. -Igen -I../../third_party/pdfium -I../../build/linux/debian_jessie_i386-sysroot/usr/include/freetype2 -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -m32 -msse2 -mfpmath=sse -mmmx -momit-leaf-frame-pointer -pthread -mstack-alignment=16 -mstackrealign -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../build/linux/debian_jessie_i386-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fvisibility-inlines-hidden -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/pdfium/fpdfsdk/formfiller/cffl_interactiveformfiller.cpp -o obj/third_party/pdfium/formfiller/cffl_interactiveformfiller.o
> In file included from ../../third_party/pdfium/fpdfsdk/formfiller/cffl_interactiveformfiller.cpp:12:
> In file included from ../../third_party/pdfium/core/fxge/cfx_pathdata.h:14:
> In file included from ../../third_party/pdfium/core/fxge/cfx_renderdevice.h:12:
> In file included from ../../third_party/pdfium/core/fxge/cfx_gemodule.h:12:
> In file included from ../../third_party/pdfium/core/fxge/cfx_fontmgr.h:13:
> In file included from ../../third_party/pdfium/core/fxge/fx_font.h:17:
> In file included from ../../third_party/pdfium/core/fxge/fx_freetype.h:11:
> In file included from ../../build/linux/debian_jessie_i386-sysroot/usr/include/freetype2/freetype.h:33:
> ../../build/linux/debian_jessie_i386-sysroot/usr/include/freetype2/config/ftconfig.h:453:5: error: 'register' storage class specifier is deprecated and incompatible with C++1z [-Werror,-Wdeprecated-register]
>     register FT_Int32  result;
>     ^~~~~~~~~
> 1 error generated.
>
> Original issue's description:
> > Support for OpenType Font Variations on Windows
> >
> > Enable support for variable fonts on Windows through using
> > SkFontMgr_Custom_Empty, a FreeType backed font-blob only SkTypeface
> > factory (no access to system fonts). We will use a hybrid DirectWrite
> > and FreeType font stack on Windows for at least as long as most of
> > Windows versions we support with Chrome still do not have native support
> > for font variations.
> >
> > Thanks to Ben Wagner for the help with enabling and prototyping this.
> >
> > BUG=700926
> >
> > Review-Url: https://codereview.chromium.org/2780133002
> > Cr-Commit-Position: refs/heads/master@{#460895}
> > Committed: https://chromium.googlesource.com/chromium/src/+/5265e65e5ea1ae3987c27f76914c9dd9a41506cd
>
> TBR=bungeman@chromium.org,bungeman@google.com,eae@chromium.org,kjellander@chromium.org,machenbach@chromium.org,drott@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=700926
>
> Review-Url: https://codereview.chromium.org/2786263002
> Cr-Commit-Position: refs/heads/master@{#460909}
> Committed: https://chromium.googlesource.com/chromium/src/+/b0e1e4e71a556604c95d25562f9447c175e541be

TBR=bungeman@chromium.org,bungeman@google.com,eae@chromium.org,kjellander@chromium.org,machenbach@chromium.org,drott@chromium.org,ortuno@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=700926

Review-Url: https://codereview.chromium.org/2792453002
Cr-Commit-Position: refs/heads/master@{#460926}