Revert "media: Use per-frame task runners in VideoTrackRecoder"
This reverts commit 1b0206984fe8d7ef9711240f0c6ff265f7e66852.

Reason for revert: Compile error on Google Chrome Linux x64:

../../content/renderer/media_recorder/h264_encoder.cc:40:7: error: no matching constructor for initialization of 'VideoTrackRecorder::Encoder'
    : Encoder(on_encoded_video_callback, bits_per_second) {
      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../content/renderer/media_recorder/video_track_recorder.h:161:30: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    DISALLOW_COPY_AND_ASSIGN(Encoder);
                             ^
../../content/renderer/media_recorder/video_track_recorder.h:88:5: note: candidate constructor not viable: requires at least 3 arguments, but 2 were provided
    Encoder(const OnEncodedVideoCB& on_encoded_video_callback,

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.chrome%2FGoogle_Chrome_Linux_x64%2F27069%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

Original change's description:
> media: Use per-frame task runners in VideoTrackRecoder
> 
> This is part of efforts to replace base::ThreadTaskRunnerHandle::Get()
> and SequencedTaskRunnerHandle::Get() with other appropriate task runners
> in the renderer.
> 
> Bug: 786332
> Change-Id: Ic48ed9957db962978f8f82c21d21aea0b634490f
> Reviewed-on: https://chromium-review.googlesource.com/890981
> Commit-Queue: Hajime Hoshi <hajimehoshi@chromium.org>
> Reviewed-by: Miguel Casas <mcasas@chromium.org>
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Reviewed-by: Mounir Lamouri (slow) <mlamouri@chromium.org>
> Reviewed-by: Alexander Timin <altimin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#533626}

TBR=mcasas@chromium.org,hajimehoshi@chromium.org,haraken@chromium.org,mlamouri@chromium.org,altimin@chromium.org

Change-Id: I800504dacec8da23affc92381cb4d0b0da7e8030
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 786332
Reviewed-on: https://chromium-review.googlesource.com/897642
Reviewed-by: Balazs Engedy <engedy@chromium.org>
Commit-Queue: Balazs Engedy <engedy@chromium.org>
Cr-Commit-Position: refs/heads/master@{#533630}