Revert of Image Capture: teach takePhoto() to accept an optional PhotoSettings dictionary (patchset #1 id:1 of https://codereview.chromium.org/2866053002/ )
Reason for revert:
This breaks build

../../third_party/WebKit/Source/modules/imagecapture/ImageCapture.cpp:570:61: error: function definition is not allowed here
    media::mojom::blink::PhotoCapabilitiesPtr capabilities) {

Sorry, Miguel

Original issue's description:
> Image Capture: teach takePhoto() to accept an optional PhotoSettings dictionary
>
> This CL:
> - Adds an optional PhotoSettings arg to takePhoto(),
>
> - cleanup: the 3 private methods used to receive mojo callbacks
>  (OnPhotoCapabilities, OnSetOptions and OnTakePhoto) get a Mojo
> prefix, for clarity.
>
> - adds a |trigger_take_photo| argument to setOptions() and a few
> others that pass it along; takePhoto() uses it to setOptions() when
> appropriate.  The sequence of method calls in ImageCapture.cpp then
> would be:
>  - without options
>    takePhoto() -> OnMojoTakePhoto()
>  - with options:
>    takePhoto(options) -> setOptions(trigger_take_photo == true)  --> OnMojoSetOptions(true) --> OnMojoPhotoCapabilities(true) --> OnMojoTakePhoto()
>
> - methods OnCapabilitiesUpdate() and OnCapabilitiesUpdateInternal()
> (which are essentially the same thing) are merged and the resulting
> method renamed to UpdateMediaTrackCapabilities() to make more
> evident what it does.
>
> BUG=718632
>
> Review-Url: https://codereview.chromium.org/2865563002
> Cr-Commit-Position: refs/heads/master@{#469766}
> (cherry picked from commit 3fd00a51e22a0ffa55d0ab14725f9f300b2fc56b)
>
> Review-Url: https://codereview.chromium.org/2866053002 .
> Cr-Commit-Position: refs/branch-heads/3071@{#451}
> Cr-Branched-From: a106f0abbf69dad349d4aaf4bcc4f5d376dd2377-refs/heads/master@{#464641}
> Committed: https://chromium.googlesource.com/chromium/src/+/dcc52283947a13edbd756eb739ee55a372fa5483

TBR=mcasas@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=718632

Review-Url: https://codereview.chromium.org/2872713002
Cr-Commit-Position: refs/branch-heads/3071@{#457}
Cr-Branched-From: a106f0abbf69dad349d4aaf4bcc4f5d376dd2377-refs/heads/master@{#464641}